import { NextResponse } from "next/server";
import { PERMISSIONS } from "@/lib/authorization/permission-policy";
import { createDataRetentionRuntime } from "@/lib/data-retention/data-retention-runtime";
import { buildProspectScopeWhere, requireProspectPermission } from "@/lib/prospect/prospect-authorization";
import { createProspectRuntime } from "@/lib/prospect/prospect-runtime";
import { prisma } from "@/lib/prisma";
import { prospectActor, prospectApiError, prospectIdempotencyKey } from "../prospect-api";
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await prospectActor(request);if("response"in auth)return auth.response;try{requireProspectPermission(auth.actor.permissions,PERMISSIONS.prospectView);const {id}=await params;const data=await prisma.prospect.findFirst({where:{id,...buildProspectScopeWhere(auth.actor.authorization,auth.actor.permissions)},include:{owner:{select:{id:true,name:true}},backupOwner:{select:{id:true,name:true}},industry:true,salesTerritory:true,contacts:{where:{deletedAt:null},orderBy:[{isPrimary:"desc"},{createdAt:"asc"}]},activities:{where:{deletedAt:null},orderBy:{createdAt:"desc"},take:200},documents:{where:{deletedAt:null},orderBy:{createdAt:"desc"}},statusHistory:{orderBy:{transitionedAt:"desc"}},assignmentHistory:{orderBy:{assignedAt:"desc"}},convertedLead:{select:{id:true,leadNumber:true,company:true}}}});if(!data)return NextResponse.json({error:{code:"RESOURCE_NOT_FOUND",message:"ไม่พบ Prospect",retryable:false,correlationId:auth.correlationId}},{status:404});return NextResponse.json({data,meta:{correlationId:auth.correlationId}});}catch(error){return prospectApiError(error,auth.correlationId);}}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await prospectActor(request);if("response"in auth)return auth.response;const key=prospectIdempotencyKey(request,auth.correlationId);if(key instanceof NextResponse)return key;try{const {id}=await params,body=await request.json(),{expectedVersion,...input}=body;const data=await createProspectRuntime().update(auth.actor,id,Number(expectedVersion),input,auth.correlationId,key);return NextResponse.json({data,meta:{correlationId:auth.correlationId}});}catch(error){return prospectApiError(error,auth.correlationId);}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await prospectActor(request);if("response"in auth)return auth.response;const key=prospectIdempotencyKey(request,auth.correlationId);if(key instanceof NextResponse)return key;try{const {id}=await params,body=await request.json();const data=await createDataRetentionRuntime().softDeleteProspect(auth.actor,id,{expectedVersion:Number(body.expectedVersion),reason:body.reason},auth.correlationId);return NextResponse.json({data,meta:{correlationId:auth.correlationId}});}catch(error){return prospectApiError(error,auth.correlationId);}}
