-- Additive Phase 1 fiscal calendar and sales-target persistence.
CREATE TABLE `FiscalCalendar` (
  `id` VARCHAR(191) NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `fiscalYearStartMonth` INTEGER NOT NULL,
  `timezone` VARCHAR(64) NOT NULL,
  `currency` CHAR(3) NOT NULL,
  `reportingCutoffHour` INTEGER NOT NULL,
  `submissionSchedule` LONGTEXT NOT NULL,
  `lockSchedule` LONGTEXT NOT NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `effectiveFrom` DATETIME(3) NOT NULL,
  `effectiveTo` DATETIME(3) NULL,
  `createdById` VARCHAR(191) NOT NULL,
  `updatedById` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL,
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `FiscalCalendar_code_key` (`code`),
  INDEX `FiscalCalendar_active_effective_idx` (`active`, `effectiveFrom`, `effectiveTo`),
  CONSTRAINT `FiscalCalendar_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FiscalCalendar_updatedById_fkey` FOREIGN KEY (`updatedById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `SalesTarget` (
  `id` VARCHAR(191) NOT NULL,
  `version` INTEGER NOT NULL DEFAULT 1,
  `targetType` VARCHAR(64) NOT NULL,
  `scopeKey` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NULL,
  `teamId` VARCHAR(191) NULL,
  `departmentId` VARCHAR(191) NULL,
  `businessUnitId` VARCHAR(191) NULL,
  `territoryId` VARCHAR(191) NULL,
  `region` VARCHAR(100) NULL,
  `productCategoryId` VARCHAR(191) NULL,
  `customerSegment` VARCHAR(100) NULL,
  `revenueType` ENUM('TOTAL_REVENUE','ONE_TIME_REVENUE','MONTHLY_RECURRING_REVENUE','ANNUAL_RECURRING_REVENUE','TOTAL_CONTRACT_VALUE','GROSS_PROFIT') NOT NULL,
  `periodType` ENUM('MONTH','QUARTER','YEAR') NOT NULL,
  `fiscalYear` INTEGER NOT NULL,
  `fiscalQuarter` INTEGER NULL,
  `fiscalMonth` INTEGER NULL,
  `targetAmount` DECIMAL(19,4) NOT NULL,
  `targetGrossProfit` DECIMAL(19,4) NULL,
  `targetRecurringRevenue` DECIMAL(19,4) NULL,
  `currency` CHAR(3) NOT NULL,
  `status` ENUM('DRAFT','ACTIVE','INACTIVE') NOT NULL DEFAULT 'DRAFT',
  `effectiveFrom` DATETIME(3) NOT NULL,
  `effectiveTo` DATETIME(3) NULL,
  `createdById` VARCHAR(191) NOT NULL,
  `updatedById` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL,
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `SalesTarget_scope_status_effective_idx` (`scopeKey`, `status`, `effectiveFrom`, `effectiveTo`),
  INDEX `SalesTarget_user_period_idx` (`userId`, `fiscalYear`, `periodType`, `status`),
  INDEX `SalesTarget_team_period_idx` (`teamId`, `fiscalYear`, `periodType`, `status`),
  INDEX `SalesTarget_business_unit_period_idx` (`businessUnitId`, `fiscalYear`, `periodType`, `status`),
  INDEX `SalesTarget_territory_period_idx` (`territoryId`, `fiscalYear`, `periodType`, `status`),
  CONSTRAINT `SalesTarget_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesTarget_teamId_fkey` FOREIGN KEY (`teamId`) REFERENCES `OrganizationUnit`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesTarget_departmentId_fkey` FOREIGN KEY (`departmentId`) REFERENCES `OrganizationUnit`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesTarget_businessUnitId_fkey` FOREIGN KEY (`businessUnitId`) REFERENCES `OrganizationUnit`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesTarget_territoryId_fkey` FOREIGN KEY (`territoryId`) REFERENCES `SalesTerritory`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesTarget_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `SalesTarget_updatedById_fkey` FOREIGN KEY (`updatedById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
