import { Pencil } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { PrintProposalButton, ProposalRestoreButton, ProposalStatusForm, ProposalVersionCompare } from "@/components/proposal-forms";
import { requireSession } from "@/lib/auth";
import { loadAuthorizationContext } from "@/lib/authorization/authorization-context";
import { PERMISSIONS, permissionPolicy } from "@/lib/authorization/permission-policy";
import { buildOpportunityScopeWhere } from "@/lib/opportunity/opportunity-query";
import { prisma } from "@/lib/prisma";

const dateTime=new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Bangkok"});

export default async function ProposalDetailPage({params}:{params:Promise<{id:string}>}){
  const session=await requireSession();const context=await loadAuthorizationContext({actorId:session.id,legacyRole:session.role});const id=(await params).id;
  const [proposal,audit]=await Promise.all([
    prisma.proposal.findFirst({where:{id,deletedAt:null,opportunity:buildOpportunityScopeWhere(context)},include:{status:true,customer:{select:{id:true,name:true,segment:true}},opportunity:{select:{id:true,name:true,stage:true}},owner:{select:{name:true}},quotes:{select:{id:true,quoteNo:true,status:true}},versions:{orderBy:{versionNumber:"desc"},include:{createdBy:{select:{name:true}},sections:{orderBy:{sortOrder:"asc"}}}}}}),
    prisma.auditEvent.findMany({where:{targetType:"Proposal",targetId:id},orderBy:{recordedAt:"desc"},take:100}),
  ]);
  if(!proposal||!proposal.versions[0])notFound();
  const canManage=permissionPolicy.allows(session,PERMISSIONS.proposalManage);const canEdit=canManage&&!proposal.status.terminal;const latest=proposal.versions[0];
  const allowed=Array.isArray(proposal.status.allowedTransitions)?proposal.status.allowedTransitions.filter((item):item is string=>typeof item==="string"):[];
  const policies=await prisma.proposalStatusTransition.findMany({where:{fromStatusCode:proposal.statusCode,toStatusCode:{in:allowed},active:true}});
  const requiredPermissions=policies.flatMap((policy)=>policy.requiredPermission?[policy.requiredPermission]:[]);const roleCodes=context.assignments.map((assignment)=>assignment.role);
  const grants=requiredPermissions.length&&roleCodes.length?await prisma.rolePermissionGrant.findMany({where:{roleCode:{in:roleCodes},permissionCode:{in:requiredPermissions}},select:{permissionCode:true}}):[];const granted=new Set(grants.map((grant)=>grant.permissionCode));
  const allowedByPolicy=policies.filter((policy)=>(!policy.makerChecker||proposal.ownerId!==session.id)&&(!policy.requiredPermission||session.role==="ADMIN"||granted.has(policy.requiredPermission))).map((policy)=>policy.toStatusCode);
  const transitions=await prisma.proposalStatusDefinition.findMany({where:{code:{in:allowedByPolicy},active:true},select:{code:true,label:true},orderBy:{sortOrder:"asc"}});
  const versionCompare=proposal.versions.map((version)=>({versionNumber:version.versionNumber,createdAt:version.createdAt.toISOString(),sections:version.sections.map((section)=>({sectionCode:section.sectionCode,title:section.title,content:section.content}))}));
  const tags=Array.isArray(latest.tags)?latest.tags.filter((item):item is string=>typeof item==="string"):[];
  return <><div className="page-head proposal-detail-head"><div><p className="eyebrow">{proposal.proposalNo} · {proposal.customer.name}</p><h1>{proposal.name}</h1><div className="proposal-meta"><span className="badge">{proposal.status.label}</span><span>v{proposal.version}</span><span>Owner: {proposal.owner.name}</span><span>Opportunity: <Link className="link" href={`/opportunities/${proposal.opportunity.id}`}>{proposal.opportunity.name}</Link></span></div></div><div className="proposal-head-actions"><PrintProposalButton/>{canEdit&&<Link className="secondary" href={`/proposals/${proposal.id}/edit`}><Pencil aria-hidden="true"/>แก้ไข</Link>}{canManage&&<Link className="primary" href={`/quotes/new?proposalId=${proposal.id}`}>Create Quotation</Link>}</div></div>
    <div className="proposal-workspace"><main><section className="card"><div className="card-header"><div><strong>Proposal Overview</strong><small>ข้อมูลจาก version {latest.versionNumber}</small></div></div><div className="card-body detail-grid"><div><p className="detail-label">Expire Date</p><p className="detail-value">{latest.expireDate?.toLocaleDateString("th-TH",{timeZone:"Asia/Bangkok"})??"—"}</p></div><div><p className="detail-label">Tags</p><p className="detail-value">{tags.join(", ")||"—"}</p></div><div className="field full"><p className="detail-label">Description</p><p>{latest.description||"—"}</p></div></div></section><div className="proposal-sections">{latest.sections.map((section)=><section className="card proposal-section" key={section.sectionCode}><div className="card-header"><div><span className="proposal-section-index">{String(section.sortOrder+1).padStart(2,"0")}</span><strong>{section.title}</strong></div><span className="badge muted">{section.sectionCode}</span></div><div className="card-body"><div className="proposal-content" style={{whiteSpace:"pre-wrap"}}>{section.content||"—"}</div></div></section>)}</div><ProposalVersionCompare versions={versionCompare}/></main><aside><ProposalStatusForm key={`status-${proposal.version}`} proposalId={proposal.id} version={proposal.version} transitions={canManage?transitions:[]}/><section className="card"><div className="card-header"><strong>Quotation</strong></div><div className="card-body">{proposal.quotes.map((quote)=><p key={quote.id}><Link className="link" href={`/quotes/${quote.id}`}>{quote.quoteNo}</Link> <span className="badge muted">{quote.status}</span></p>)}{!proposal.quotes.length&&<p className="help">ยังไม่มี Quotation ที่เชื่อมกับ Proposal นี้</p>}</div></section></aside></div>
    <section className="card proposal-history"><div className="card-header"><strong>Version &amp; Audit Timeline</strong></div><div className="card-body"><div className="timeline">{proposal.versions.map((version)=><article key={version.id}><span/><div><strong>Version {version.versionNumber} · {version.statusCode}</strong><p>{dateTime.format(version.createdAt)} · {version.createdBy.name}{version.aiProviderModel?` · AI ${version.aiProviderModel}`:""}</p>{version.versionNumber<proposal.version&&canManage&&<ProposalRestoreButton key={`restore-${proposal.version}-${version.versionNumber}`} proposalId={proposal.id} expectedVersion={proposal.version} sourceVersionNumber={version.versionNumber} disabled={proposal.status.terminal}/>}</div></article>)}{audit.map((event)=><article key={event.id}><span/><div><strong>{event.action}</strong><p>{dateTime.format(event.recordedAt)} · correlation {event.correlationId.slice(0,8)}</p></div></article>)}</div></div></section>
  </>;
}
