import Link from "next/link";
import { BookOpen, Search } from "lucide-react";
import { helpAudienceLabels, helpArticles, searchHelpArticles } from "@/lib/help-center";

export default async function HelpCenterPage({ searchParams }: { searchParams: Promise<{ q?: string; audience?: string }> }) {
  const { q = "", audience = "" } = await searchParams; const articles = searchHelpArticles(q, audience); const categories = [...new Set(helpArticles.map((article) => article.category))];
  return <><section className="help-hero"><div className="help-hero-icon"><BookOpen/></div><p className="eyebrow">Help Center</p><h1>ศูนย์ช่วยเหลือ NTOP</h1><p>ค้นหาวิธีใช้งาน Customer, Opportunity, Pipeline, Quotation, Approval และการตั้งค่าระบบ</p><form className="help-search"><label><Search/><input name="q" defaultValue={q} placeholder="ค้นหา เช่น floor price, transition, approval"/></label><select name="audience" defaultValue={audience}><option value="">ทุกบทบาท</option>{Object.entries(helpAudienceLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><button className="primary">ค้นหา</button></form></section>
    <div className="help-layout"><aside className="help-categories"><h2>หมวดหมู่</h2>{categories.map((category)=><span key={category}>{category}</span>)}</aside><section><div className="help-result-head"><p>พบบทความ {articles.length} รายการ</p>{(q||audience)&&<Link href="/help">ล้างตัวกรอง</Link>}</div><div className="help-cards">{articles.map((article)=><Link className="help-card" href={`/help/${article.slug}`} key={article.slug}><div><span className="badge">{article.category}</span><small>{article.readingMinutes} นาที · อัปเดต {article.updatedAt}</small></div><h2>{article.title}</h2><p>{article.summary}</p><div>{article.audience.map((item)=><span key={item}>{helpAudienceLabels[item]}</span>)}</div></Link>)}{!articles.length&&<div className="card empty">ไม่พบบทความที่ตรงกับคำค้นหา</div>}</div></section></div></>;
}
