import { createApprovalPolicy, createAuthorityGrant, createRoleAssignment, createTransitionPolicy, confirmProductCost } from "@/app/actions/workflow-admin";
import { AUTHORIZATION_SCOPES, ENTERPRISE_ROLES } from "@/lib/authorization/enterprise-role-policy";
import { PERMISSIONS } from "@/lib/authorization/permission-policy";
import { requirePermission } from "@/lib/authorization/require-permission";
import { prisma } from "@/lib/prisma";

const stages = ["QUALIFY", "DISCOVER", "SOLUTION", "PROPOSAL", "NEGOTIATION", "WON", "LOST", "CANCELLED"];
const commands = ["FORWARD", "RETURN", "LOST", "REOPEN", "CANCEL", "WON"];
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Bangkok" }).format(new Date());

export default async function WorkflowAdministrationPage() {
  await requirePermission(PERMISSIONS.workflowConfigManage);
  const [transitions, policies, grants, users, products, orgs, assignments] = await Promise.all([
    prisma.opportunityTransitionPolicyVersion.findMany({ orderBy: [{ policyCode: "asc" }, { version: "desc" }], take: 100 }), prisma.approvalPolicy.findMany({ include: { activeVersion: true }, orderBy: { code: "asc" } }), prisma.approvalAuthorityGrant.findMany({ orderBy: { createdAt: "desc" }, take: 100 }), prisma.user.findMany({ select: { id: true, name: true, email: true }, orderBy: { name: "asc" } }), prisma.product.findMany({ select: { id: true, code: true, name: true, standardCost: true, costConfirmedAt: true }, orderBy: { code: "asc" } }), prisma.organizationUnit.findMany({ select: { id: true, code: true, name: true }, orderBy: { code: "asc" } }), prisma.userRoleAssignment.findMany({ orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const effective = today();
  return <><div className="page-head"><div><p className="eyebrow">Administration</p><h1>Workflow &amp; Authority</h1><p>ทุกการเปลี่ยนนโยบายสร้าง version ใหม่และเขียน audit log</p></div></div><div className="grid-2">
    <form action={createTransitionPolicy} className="card form-card"><div className="card-body"><h2>Transition policy version</h2><input className="control" name="policyCode" placeholder="Policy code" required/><select className="control" name="command">{commands.map(x=><option key={x}>{x}</option>)}</select><select className="control" name="fromStage">{stages.map(x=><option key={x}>{x}</option>)}</select><select className="control" name="toStage">{stages.map(x=><option key={x}>{x}</option>)}</select><input className="control" name="requiredFields" placeholder="requiredFields comma-separated"/><input className="control" name="requiredPermission" defaultValue={PERMISSIONS.opportunityTransition} required/><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/><input className="control" type="date" name="effectiveTo"/><button className="primary">สร้าง version</button></div></form>
    <form action={createApprovalPolicy} className="card form-card"><div className="card-body"><h2>Approval policy version</h2><input className="control" name="code" placeholder="Policy code" required/><textarea className="control" name="definition" rows={10} defaultValue={'{"submissionGates":{"confirmedCostRequired":true},"rules":[],"fallbackSteps":[]}'} required/><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/><input className="control" type="date" name="effectiveTo"/><button className="primary">สร้างและ activate</button></div></form>
    <form action={createAuthorityGrant} className="card form-card"><div className="card-body"><h2>Approver authority grant</h2><select className="control" name="roleCode">{ENTERPRISE_ROLES.map(x=><option key={x}>{x}</option>)}</select><input className="control" name="permissionCode" defaultValue={PERMISSIONS.approvalDecide} required/><select className="control" name="organizationUnitId"><option value="">ทุกหน่วยงาน</option>{orgs.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><input className="control" name="customerSegment" placeholder="Customer segment (optional)"/><input className="control" name="maximumAmount" inputMode="decimal" placeholder="Maximum amount" required/><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/><input className="control" type="date" name="effectiveTo"/><button className="primary">เพิ่ม authority</button></div></form>
    <form action={createRoleAssignment} className="card form-card"><div className="card-body"><h2>Role assignment</h2><select className="control" name="userId">{users.map(x=><option key={x.id} value={x.id}>{x.name} — {x.email}</option>)}</select><select className="control" name="roleCode">{ENTERPRISE_ROLES.map(x=><option key={x}>{x}</option>)}</select><select className="control" name="scopeCode">{AUTHORIZATION_SCOPES.map(x=><option key={x}>{x}</option>)}</select><select className="control" name="organizationUnitId"><option value="">ไม่ระบุหน่วยงาน</option>{orgs.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/><input className="control" type="date" name="effectiveTo"/><button className="primary">มอบหมาย role</button></div></form>
    <form action={confirmProductCost} className="card form-card"><div className="card-body"><h2>Confirmed product cost</h2><select className="control" name="productId">{products.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><input className="control" name="standardCost" inputMode="decimal" placeholder="Confirmed cost" required/><input className="control" type="date" name="confirmedAt" defaultValue={effective} required/><button className="primary">ยืนยันต้นทุน</button></div></form>
  </div><section className="card" style={{marginTop:20}}><div className="card-header">Current configuration</div><div className="card-body"><p>Transition versions: {transitions.length} · Approval policies: {policies.length} · Authority grants: {grants.length} · Role assignments: {assignments.length}</p><p>Products missing confirmed cost: {products.filter(x=>!x.costConfirmedAt).length}</p></div></section></>;
}
