import {
  confirmProductCost,
  createAmountApprovalPolicy,
  createAuthorityGrant,
  deactivateAuthorityGrant,
  createRoleAssignment,
  createTransitionPolicy,
  updateApprovalSystemMode,
  updateApprovalWorkflowMode,
} from "@/app/actions/workflow-admin";
import { APPROVAL_MODES } from "@/lib/approval/approval-control";
import { AUTHORIZATION_SCOPES, ENTERPRISE_ROLES } from "@/lib/authorization/enterprise-role-policy";
import { PERMISSIONS } from "@/lib/authorization/permission-policy";
import { requirePermission } from "@/lib/authorization/require-permission";
import { prisma } from "@/lib/prisma";

const stages = ["QUALIFY", "DISCOVER", "SOLUTION", "PROPOSAL", "NEGOTIATION", "WON", "LOST", "CANCELLED"];
const commands = ["FORWARD", "RETURN", "LOST", "REOPEN", "CANCEL", "WON"];
const approvalPermissions = [PERMISSIONS.approvalDecide, PERMISSIONS.proposalManagerReview, PERMISSIONS.proposalDirectorApprove, PERMISSIONS.solutionDesignTechnicalApprove, PERMISSIONS.solutionDesignCommercialApprove, PERMISSIONS.siteSurveyResultApprove, PERMISSIONS.boqApprove, PERMISSIONS.contractApprove];
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Bangkok" }).format(new Date());

export default async function WorkflowAdministrationPage() {
  await requirePermission(PERMISSIONS.workflowConfigManage);
  const [system, workflows, transitions, grants, users, products, orgs, assignments] = await Promise.all([
    prisma.approvalSystemConfiguration.findUnique({ where: { id: "approval_system" } }),
    prisma.approvalWorkflowConfiguration.findMany({ include: { policy: { include: { activeVersion: true, versions: { orderBy: { version: "desc" }, take: 5 } } } }, orderBy: { displayOrder: "asc" } }),
    prisma.opportunityTransitionPolicyVersion.findMany({ orderBy: [{ policyCode: "asc" }, { version: "desc" }], take: 100 }),
    prisma.approvalAuthorityGrant.findMany({ where: { active: true }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.user.findMany({ select: { id: true, name: true, email: true }, orderBy: { name: "asc" } }),
    prisma.product.findMany({ select: { id: true, code: true, name: true, standardCost: true, costConfirmedAt: true }, orderBy: { code: "asc" } }),
    prisma.organizationUnit.findMany({ select: { id: true, code: true, name: true }, orderBy: { code: "asc" } }),
    prisma.userRoleAssignment.findMany({ orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const effective = today();
  const global = system ?? { mode: "DISABLED", version: 1, reason: "ยังไม่ได้สร้าง configuration" };
  return <>
    <div className="page-head"><div><p className="eyebrow">Administration</p><h1>Approval Control Center</h1><p>ตั้งค่า Approval ทั้งระบบจากหน้าเดียว ทุก policy เป็น versioned data และทุก workflow เริ่มต้นแบบ Disabled</p></div><span className={`badge ${global.mode === "DISABLED" ? "muted" : "warning"}`}>Global {global.mode}</span></div>
    <section className="card" style={{ marginBottom: 20 }}><div className="card-header"><div><strong>Global Approval Mode</strong><small>Global Disabled มีผลเหนือการตั้งค่าราย workflow และไม่มีการ auto-approve</small></div></div><div className="card-body"><form action={updateApprovalSystemMode} className="form-grid"><input type="hidden" name="expectedVersion" value={global.version}/><label className="field"><span>Mode</span><select className="control" name="mode" defaultValue={global.mode}>{APPROVAL_MODES.map((mode)=><option key={mode}>{mode}</option>)}</select></label><label className="field full"><span>เหตุผลการเปลี่ยน</span><input className="control" name="reason" minLength={5} maxLength={1000} required defaultValue={global.reason ?? ""}/></label><div className="field full"><button className="primary">บันทึก Global Mode</button></div></form></div></section>
    <section className="card" style={{ marginBottom: 20 }}><div className="card-header"><div><strong>Approval Workflows</strong><small>ต้อง Publish policy ที่มี approver step ก่อนเปิด Enforced</small></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Workflow</th><th>Amount source</th><th>Policy</th><th>Mode / control</th></tr></thead><tbody>{workflows.map((workflow)=><tr key={workflow.id}><td><strong>{workflow.name}</strong><br/><small>{workflow.code} · {workflow.moduleCode}</small></td><td>{workflow.amountSource ?? "ไม่ใช้วงเงิน"}</td><td>{workflow.policy.activeVersion ? `v${workflow.policy.activeVersion.version}` : "ยังไม่มี Published policy"}<br/><small>{workflow.policy.versions.length} versions ล่าสุด</small></td><td><form action={updateApprovalWorkflowMode} className="approval-workflow-mode-form"><input type="hidden" name="workflowCode" value={workflow.code}/><input type="hidden" name="expectedVersion" value={workflow.version}/><select className="control" name="mode" defaultValue={workflow.mode}>{APPROVAL_MODES.map((mode)=><option key={mode}>{mode}</option>)}</select><input className="control" name="reason" minLength={5} maxLength={1000} required defaultValue={workflow.reason ?? "ตั้งค่าจาก Approval Control Center"}/><button className="secondary">บันทึก</button></form></td></tr>)}</tbody></table></div></section>
    <div className="grid-2">
      <form action={createAmountApprovalPolicy} className="card form-card"><div className="card-body"><h2>Publish Approval Policy</h2><p className="help">Workflow ที่มี Amount Source ใช้ 3 tiers; workflow อื่นใช้ Tier 1 role เป็น reviewer หลัก</p><select className="control" name="workflowCode">{workflows.map((workflow)=><option value={workflow.code} key={workflow.code}>{workflow.name}</option>)}</select><select className="control" name="requiredPermission">{approvalPermissions.map((permission)=><option key={permission}>{permission}</option>)}</select><div className="form-grid"><label className="field"><span>Tier 1 maximum</span><input className="control" name="tier1Maximum" inputMode="decimal" defaultValue="10000000.0000"/></label><label className="field"><span>Tier 1 role / reviewer</span><select className="control" name="tier1RoleCode">{ENTERPRISE_ROLES.map((role)=><option key={role}>{role}</option>)}</select></label><label className="field"><span>Tier 2 maximum</span><input className="control" name="tier2Maximum" inputMode="decimal" defaultValue="100000000.0000"/></label><label className="field"><span>Tier 2 role</span><select className="control" name="tier2RoleCode">{ENTERPRISE_ROLES.map((role)=><option key={role}>{role}</option>)}</select></label><label className="field"><span>Tier 3 role</span><select className="control" name="tier3RoleCode">{ENTERPRISE_ROLES.map((role)=><option key={role}>{role}</option>)}</select></label><label className="field"><span>Effective from</span><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/></label></div><label className="field"><input type="checkbox" name="makerChecker" defaultChecked/> บังคับ maker-checker</label><input className="control" type="date" name="effectiveTo"/><button className="primary">Publish version (ยังไม่ Enable)</button></div></form>
      <form action={createAuthorityGrant} className="card form-card"><div className="card-body"><h2>Approver Authority Grant</h2><label className="field"><span>Role</span><select className="control" name="roleCode">{ENTERPRISE_ROLES.map((role)=><option key={role}>{role}</option>)}</select></label><label className="field"><span>Permission</span><select className="control" name="permissionCode">{approvalPermissions.map((permission)=><option key={permission}>{permission}</option>)}</select></label><label className="field"><span>Organization</span><select className="control" name="organizationUnitId"><option value="">ทุกหน่วยงาน</option>{orgs.map((org)=><option key={org.id} value={org.id}>{org.code} — {org.name}</option>)}</select></label><label className="field"><span>Customer segment</span><input className="control" name="customerSegment" placeholder="Optional"/></label><label className="field"><span>Maximum amount</span><input className="control" name="maximumAmount" inputMode="decimal" required/></label><label className="field"><span>Effective from</span><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/></label><label className="field"><span>Effective to</span><input className="control" type="date" name="effectiveTo"/></label><button className="primary">เพิ่ม Authority</button></div></form>
      <form action={createTransitionPolicy} className="card form-card"><div className="card-body"><h2>Opportunity Transition Policy</h2><label className="field"><span>Policy code</span><input className="control" name="policyCode" required/></label><label className="field"><span>Command</span><select className="control" name="command">{commands.map((command)=><option key={command}>{command}</option>)}</select></label><label className="field"><span>From stage</span><select className="control" name="fromStage">{stages.map((stage)=><option key={stage}>{stage}</option>)}</select></label><label className="field"><span>To stage</span><select className="control" name="toStage">{stages.map((stage)=><option key={stage}>{stage}</option>)}</select></label><label className="field"><span>Required fields</span><input className="control" name="requiredFields" placeholder="Comma-separated"/></label><label className="field"><span>Required permission</span><input className="control" name="requiredPermission" defaultValue={PERMISSIONS.opportunityTransition} required/></label><label className="field"><span>Effective from</span><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/></label><label className="field"><span>Effective to</span><input className="control" type="date" name="effectiveTo"/></label><button className="primary">สร้าง Transition version</button></div></form>
      <form action={createRoleAssignment} className="card form-card"><div className="card-body"><h2>Role Assignment</h2><label className="field"><span>User</span><select className="control" name="userId">{users.map((user)=><option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select></label><label className="field"><span>Role</span><select className="control" name="roleCode">{ENTERPRISE_ROLES.map((role)=><option key={role}>{role}</option>)}</select></label><label className="field"><span>Scope</span><select className="control" name="scopeCode">{AUTHORIZATION_SCOPES.map((scope)=><option key={scope}>{scope}</option>)}</select></label><label className="field"><span>Organization</span><select className="control" name="organizationUnitId"><option value="">ไม่ระบุหน่วยงาน</option>{orgs.map((org)=><option key={org.id} value={org.id}>{org.code} — {org.name}</option>)}</select></label><label className="field"><span>Effective from</span><input className="control" type="date" name="effectiveFrom" defaultValue={effective} required/></label><label className="field"><span>Effective to</span><input className="control" type="date" name="effectiveTo"/></label><button className="primary">มอบหมาย Role</button></div></form>
      <form action={confirmProductCost} className="card form-card"><div className="card-body"><h2>Confirmed Product Cost</h2><label className="field"><span>Product</span><select className="control" name="productId">{products.map((product)=><option key={product.id} value={product.id}>{product.code} — {product.name}</option>)}</select></label><label className="field"><span>Confirmed cost</span><input className="control" name="standardCost" inputMode="decimal" required/></label><label className="field"><span>Confirmed at</span><input className="control" type="date" name="confirmedAt" defaultValue={effective} required/></label><button className="primary">ยืนยันต้นทุน</button></div></form>
    </div>
    <section className="card" style={{ marginTop: 20 }}><div className="card-header"><div><strong>Active Approval Authorities</strong><small>วงเงินและ scope ของผู้อนุมัติทุก workflow จัดการจากหน้านี้</small></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Role / Permission</th><th>Organization / Segment</th><th>Maximum amount</th><th>Effective period</th><th>Control</th></tr></thead><tbody>{grants.map((grant)=><tr key={grant.id}><td><strong>{grant.roleCode}</strong><br/><small>{grant.permissionCode}</small></td><td>{orgs.find((org)=>org.id===grant.organizationUnitId)?.name??"ทุกหน่วยงาน"}<br/><small>{grant.customerSegment??"ทุก segment"}</small></td><td>{grant.maximumAmount.toString()}</td><td>{grant.effectiveFrom.toLocaleDateString("th-TH",{timeZone:"Asia/Bangkok"})} – {grant.effectiveTo?.toLocaleDateString("th-TH",{timeZone:"Asia/Bangkok"})??"ไม่มีกำหนด"}</td><td><form action={deactivateAuthorityGrant}><input type="hidden" name="grantId" value={grant.id}/><button className="danger">ปิด Authority</button></form></td></tr>)}{!grants.length&&<tr><td colSpan={5}>ยังไม่มี Active Authority Grant</td></tr>}</tbody></table></div></section>
    <section className="card" style={{ marginTop: 20 }}><div className="card-header">Configuration Summary</div><div className="card-body"><p>Approval workflows: {workflows.length} · Disabled: {workflows.filter((workflow)=>workflow.mode === "DISABLED").length} · Transition versions: {transitions.length}</p><p>Authority grants: {grants.length} · Role assignments: {assignments.length} · Products missing confirmed cost: {products.filter((product)=>!product.costConfirmedAt).length}</p></div></section>
  </>;
}
