import { LeadStatus } from "@prisma/client";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { loadAuthorizationContext } from "@/lib/authorization/authorization-context";
import { createLeadAuditWriter } from "@/lib/lead/lead-runtime";
import { buildLeadScopeWhere } from "@/lib/lead/prisma-lead-repository";
import { LEAD_EXPORT_ROLES } from "@/lib/lead/lead-rules";
import { prisma } from "@/lib/prisma";
import { workflowApiError,workflowCorrelationId,workflowUnauthenticated } from "../../workflow-api-response";
const csv=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
export async function GET(request:Request){const correlationId=workflowCorrelationId(request);const session=await getSession();if(!session)return workflowUnauthenticated(correlationId);try{const authorization=await loadAuthorizationContext({actorId:session.id,legacyRole:session.role});if(!authorization.assignments.some(item=>(LEAD_EXPORT_ROLES as readonly string[]).includes(item.role)))return NextResponse.json({error:{code:"FORBIDDEN",message:"ไม่มีสิทธิ์ Export Lead",retryable:false,correlationId}},{status:403});const url=new URL(request.url);const requestedStatus=url.searchParams.get("status");const status=requestedStatus&&Object.values(LeadStatus).includes(requestedStatus as LeadStatus)?requestedStatus as LeadStatus:undefined;const marketingOnly=authorization.assignments.some(item=>item.role==="MARKETING")&&!authorization.assignments.some(item=>item.role==="ADMIN");const rows=await prisma.$transaction(async transaction=>{const result=await transaction.lead.findMany({where:{AND:[buildLeadScopeWhere(authorization),status?{status}:{status:{not:LeadStatus.ARCHIVED}}]},select:{leadNumber:true,company:true,contactName:true,contactEmail:true,contactPhone:true,source:true,status:true,temperature:true,score:true,estimatedBudget:true,nextFollowUpAt:true},orderBy:[{updatedAt:"desc"},{id:"desc"}],take:5000});await createLeadAuditWriter().append({actorId:session.id,action:"lead.export",targetType:"LeadExport",targetId:correlationId,outcome:"SUCCESS",correlationId,data:{rowCount:result.length,status:status??null}},{transaction});return result;});const header=["leadNumber","company","contactName","contactEmail","contactPhone","source","status","temperature","score","estimatedBudget","nextFollowUpAt"];const body=rows.map(row=>[row.leadNumber,row.company,row.contactName,row.contactEmail,row.contactPhone,row.source,row.status,row.temperature,row.score,marketingOnly?"":row.estimatedBudget?.toString(),row.nextFollowUpAt?.toISOString()].map(csv).join(","));return new NextResponse([header.join(","),...body].join("\r\n"),{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=leads.csv","x-correlation-id":correlationId}});}catch(error){return workflowApiError(error,correlationId);}}
