CREATE TABLE `ProvinceReference` (
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `region` VARCHAR(100) NOT NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `displayOrder` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `ProvinceReference_name_key` (`name`),
  INDEX `ProvinceReference_active_displayOrder_idx` (`active`, `displayOrder`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `ProvinceReference` (`code`, `name`, `region`, `active`, `displayOrder`, `updatedAt`) VALUES
  ('10','กรุงเทพมหานคร','ภาคกลาง',true,10,CURRENT_TIMESTAMP(3)),
  ('11','สมุทรปราการ','ภาคกลาง',true,20,CURRENT_TIMESTAMP(3)),
  ('12','นนทบุรี','ภาคกลาง',true,30,CURRENT_TIMESTAMP(3)),
  ('13','ปทุมธานี','ภาคกลาง',true,40,CURRENT_TIMESTAMP(3)),
  ('14','พระนครศรีอยุธยา','ภาคกลาง',true,50,CURRENT_TIMESTAMP(3)),
  ('15','อ่างทอง','ภาคกลาง',true,60,CURRENT_TIMESTAMP(3)),
  ('16','ลพบุรี','ภาคกลาง',true,70,CURRENT_TIMESTAMP(3)),
  ('17','สิงห์บุรี','ภาคกลาง',true,80,CURRENT_TIMESTAMP(3)),
  ('18','ชัยนาท','ภาคกลาง',true,90,CURRENT_TIMESTAMP(3)),
  ('19','สระบุรี','ภาคกลาง',true,100,CURRENT_TIMESTAMP(3)),
  ('20','ชลบุรี','ภาคตะวันออก',true,110,CURRENT_TIMESTAMP(3)),
  ('21','ระยอง','ภาคตะวันออก',true,120,CURRENT_TIMESTAMP(3)),
  ('22','จันทบุรี','ภาคตะวันออก',true,130,CURRENT_TIMESTAMP(3)),
  ('23','ตราด','ภาคตะวันออก',true,140,CURRENT_TIMESTAMP(3)),
  ('24','ฉะเชิงเทรา','ภาคตะวันออก',true,150,CURRENT_TIMESTAMP(3)),
  ('25','ปราจีนบุรี','ภาคตะวันออก',true,160,CURRENT_TIMESTAMP(3)),
  ('26','นครนายก','ภาคกลาง',true,170,CURRENT_TIMESTAMP(3)),
  ('27','สระแก้ว','ภาคตะวันออก',true,180,CURRENT_TIMESTAMP(3)),
  ('30','นครราชสีมา','ภาคตะวันออกเฉียงเหนือ',true,190,CURRENT_TIMESTAMP(3)),
  ('31','บุรีรัมย์','ภาคตะวันออกเฉียงเหนือ',true,200,CURRENT_TIMESTAMP(3)),
  ('32','สุรินทร์','ภาคตะวันออกเฉียงเหนือ',true,210,CURRENT_TIMESTAMP(3)),
  ('33','ศรีสะเกษ','ภาคตะวันออกเฉียงเหนือ',true,220,CURRENT_TIMESTAMP(3)),
  ('34','อุบลราชธานี','ภาคตะวันออกเฉียงเหนือ',true,230,CURRENT_TIMESTAMP(3)),
  ('35','ยโสธร','ภาคตะวันออกเฉียงเหนือ',true,240,CURRENT_TIMESTAMP(3)),
  ('36','ชัยภูมิ','ภาคตะวันออกเฉียงเหนือ',true,250,CURRENT_TIMESTAMP(3)),
  ('37','อำนาจเจริญ','ภาคตะวันออกเฉียงเหนือ',true,260,CURRENT_TIMESTAMP(3)),
  ('38','บึงกาฬ','ภาคตะวันออกเฉียงเหนือ',true,270,CURRENT_TIMESTAMP(3)),
  ('39','หนองบัวลำภู','ภาคตะวันออกเฉียงเหนือ',true,280,CURRENT_TIMESTAMP(3)),
  ('40','ขอนแก่น','ภาคตะวันออกเฉียงเหนือ',true,290,CURRENT_TIMESTAMP(3)),
  ('41','อุดรธานี','ภาคตะวันออกเฉียงเหนือ',true,300,CURRENT_TIMESTAMP(3)),
  ('42','เลย','ภาคตะวันออกเฉียงเหนือ',true,310,CURRENT_TIMESTAMP(3)),
  ('43','หนองคาย','ภาคตะวันออกเฉียงเหนือ',true,320,CURRENT_TIMESTAMP(3)),
  ('44','มหาสารคาม','ภาคตะวันออกเฉียงเหนือ',true,330,CURRENT_TIMESTAMP(3)),
  ('45','ร้อยเอ็ด','ภาคตะวันออกเฉียงเหนือ',true,340,CURRENT_TIMESTAMP(3)),
  ('46','กาฬสินธุ์','ภาคตะวันออกเฉียงเหนือ',true,350,CURRENT_TIMESTAMP(3)),
  ('47','สกลนคร','ภาคตะวันออกเฉียงเหนือ',true,360,CURRENT_TIMESTAMP(3)),
  ('48','นครพนม','ภาคตะวันออกเฉียงเหนือ',true,370,CURRENT_TIMESTAMP(3)),
  ('49','มุกดาหาร','ภาคตะวันออกเฉียงเหนือ',true,380,CURRENT_TIMESTAMP(3)),
  ('50','เชียงใหม่','ภาคเหนือ',true,390,CURRENT_TIMESTAMP(3)),
  ('51','ลำพูน','ภาคเหนือ',true,400,CURRENT_TIMESTAMP(3)),
  ('52','ลำปาง','ภาคเหนือ',true,410,CURRENT_TIMESTAMP(3)),
  ('53','อุตรดิตถ์','ภาคเหนือ',true,420,CURRENT_TIMESTAMP(3)),
  ('54','แพร่','ภาคเหนือ',true,430,CURRENT_TIMESTAMP(3)),
  ('55','น่าน','ภาคเหนือ',true,440,CURRENT_TIMESTAMP(3)),
  ('56','พะเยา','ภาคเหนือ',true,450,CURRENT_TIMESTAMP(3)),
  ('57','เชียงราย','ภาคเหนือ',true,460,CURRENT_TIMESTAMP(3)),
  ('58','แม่ฮ่องสอน','ภาคเหนือ',true,470,CURRENT_TIMESTAMP(3)),
  ('60','นครสวรรค์','ภาคเหนือ',true,480,CURRENT_TIMESTAMP(3)),
  ('61','อุทัยธานี','ภาคเหนือ',true,490,CURRENT_TIMESTAMP(3)),
  ('62','กำแพงเพชร','ภาคเหนือ',true,500,CURRENT_TIMESTAMP(3)),
  ('63','ตาก','ภาคตะวันตก',true,510,CURRENT_TIMESTAMP(3)),
  ('64','สุโขทัย','ภาคเหนือ',true,520,CURRENT_TIMESTAMP(3)),
  ('65','พิษณุโลก','ภาคเหนือ',true,530,CURRENT_TIMESTAMP(3)),
  ('66','พิจิตร','ภาคเหนือ',true,540,CURRENT_TIMESTAMP(3)),
  ('67','เพชรบูรณ์','ภาคเหนือ',true,550,CURRENT_TIMESTAMP(3)),
  ('70','ราชบุรี','ภาคตะวันตก',true,560,CURRENT_TIMESTAMP(3)),
  ('71','กาญจนบุรี','ภาคตะวันตก',true,570,CURRENT_TIMESTAMP(3)),
  ('72','สุพรรณบุรี','ภาคกลาง',true,580,CURRENT_TIMESTAMP(3)),
  ('73','นครปฐม','ภาคกลาง',true,590,CURRENT_TIMESTAMP(3)),
  ('74','สมุทรสาคร','ภาคกลาง',true,600,CURRENT_TIMESTAMP(3)),
  ('75','สมุทรสงคราม','ภาคกลาง',true,610,CURRENT_TIMESTAMP(3)),
  ('76','เพชรบุรี','ภาคตะวันตก',true,620,CURRENT_TIMESTAMP(3)),
  ('77','ประจวบคีรีขันธ์','ภาคตะวันตก',true,630,CURRENT_TIMESTAMP(3)),
  ('80','นครศรีธรรมราช','ภาคใต้',true,640,CURRENT_TIMESTAMP(3)),
  ('81','กระบี่','ภาคใต้',true,650,CURRENT_TIMESTAMP(3)),
  ('82','พังงา','ภาคใต้',true,660,CURRENT_TIMESTAMP(3)),
  ('83','ภูเก็ต','ภาคใต้',true,670,CURRENT_TIMESTAMP(3)),
  ('84','สุราษฎร์ธานี','ภาคใต้',true,680,CURRENT_TIMESTAMP(3)),
  ('85','ระนอง','ภาคใต้',true,690,CURRENT_TIMESTAMP(3)),
  ('86','ชุมพร','ภาคใต้',true,700,CURRENT_TIMESTAMP(3)),
  ('90','สงขลา','ภาคใต้',true,710,CURRENT_TIMESTAMP(3)),
  ('91','สตูล','ภาคใต้',true,720,CURRENT_TIMESTAMP(3)),
  ('92','ตรัง','ภาคใต้',true,730,CURRENT_TIMESTAMP(3)),
  ('93','พัทลุง','ภาคใต้',true,740,CURRENT_TIMESTAMP(3)),
  ('94','ปัตตานี','ภาคใต้',true,750,CURRENT_TIMESTAMP(3)),
  ('95','ยะลา','ภาคใต้',true,760,CURRENT_TIMESTAMP(3)),
  ('96','นราธิวาส','ภาคใต้',true,770,CURRENT_TIMESTAMP(3));

ALTER TABLE `Lead`
  ADD COLUMN `companyNameEnglish` VARCHAR(255) NULL,
  ADD COLUMN `customerType` VARCHAR(100) NULL,
  ADD COLUMN `segment` VARCHAR(100) NULL,
  ADD COLUMN `subIndustry` VARCHAR(191) NULL,
  ADD COLUMN `companySize` VARCHAR(100) NULL,
  ADD COLUMN `numberOfEmployees` INTEGER NULL,
  ADD COLUMN `address` TEXT NULL,
  ADD COLUMN `subDistrict` VARCHAR(191) NULL,
  ADD COLUMN `district` VARCHAR(191) NULL,
  ADD COLUMN `province` VARCHAR(191) NULL,
  ADD COLUMN `postalCode` VARCHAR(20) NULL,
  ADD COLUMN `region` VARCHAR(100) NULL,
  ADD COLUMN `currentTelecomProvider` TEXT NULL,
  ADD COLUMN `currentInternetProvider` TEXT NULL,
  ADD COLUMN `currentCloudProvider` TEXT NULL,
  ADD COLUMN `currentSecurityProvider` TEXT NULL,
  ADD COLUMN `aiSummary` TEXT NULL,
  ADD COLUMN `aiOpportunityScore` INTEGER NULL,
  ADD COLUMN `aiConfidenceScore` INTEGER NULL,
  ADD COLUMN `aiRiskScore` INTEGER NULL,
  ADD COLUMN `suggestedNextAction` TEXT NULL,
  ADD COLUMN `enrichmentData` JSON NULL,
  ADD COLUMN `enrichmentStatus` ENUM('NOT_REQUESTED','QUEUED','PROCESSING','READY','CONFIRMED','REJECTED','FAILED') NOT NULL DEFAULT 'NOT_REQUESTED',
  ADD COLUMN `enrichmentUpdatedAt` DATETIME(3) NULL,
  ADD INDEX `Lead_segment_subIndustry_idx` (`segment`, `subIndustry`),
  ADD INDEX `Lead_province_idx` (`province`);

UPDATE `Lead` AS `lead`
INNER JOIN `Prospect` AS `prospect` ON `prospect`.`convertedLeadId` = `lead`.`id`
SET
  `lead`.`companyNameEnglish` = `prospect`.`companyNameEnglish`,
  `lead`.`customerType` = `prospect`.`customerType`,
  `lead`.`segment` = `prospect`.`organizationType`,
  `lead`.`subIndustry` = `prospect`.`subIndustry`,
  `lead`.`companySize` = `prospect`.`companySize`,
  `lead`.`numberOfEmployees` = `prospect`.`numberOfEmployees`,
  `lead`.`address` = `prospect`.`address`,
  `lead`.`subDistrict` = `prospect`.`subDistrict`,
  `lead`.`district` = `prospect`.`district`,
  `lead`.`province` = `prospect`.`province`,
  `lead`.`postalCode` = `prospect`.`postalCode`,
  `lead`.`region` = `prospect`.`region`,
  `lead`.`currentTelecomProvider` = `prospect`.`currentTelecomProvider`,
  `lead`.`currentInternetProvider` = `prospect`.`currentInternetProvider`,
  `lead`.`currentCloudProvider` = `prospect`.`currentCloudProvider`,
  `lead`.`currentSecurityProvider` = `prospect`.`currentSecurityProvider`;
