import { Prisma, PrismaClient } from "@prisma/client";
import type { AuthorizationContext } from "../authorization/authorization-context";
import { buildOpportunityScopeWhere } from "../opportunity/opportunity-query";
import type { ContractEditInput, ContractItemInput } from "./contracts";
import type { ContractRecord, ContractRepository } from "./contract-service";

type Tx = Prisma.TransactionClient;
const include = { status: { select: { terminal: true } }, versions: { orderBy: { versionNumber: "desc" as const }, take: 1, include: { items: { orderBy: { sortOrder: "asc" as const } } } }, signatures: { where: { status: "VERIFIED", documentVersion: { malwareScanStatus: "CLEAN" } }, select: { partyCode: true } } } as const;

function scope(context: AuthorizationContext): Prisma.ContractWhereInput {
  if (context.assignments.some((a) => a.scope === "ENTERPRISE")) return {};
  const units = context.assignments.flatMap((a) => (a.organizationUnitId && (a.scope === "ORG_UNIT" || a.scope === "TEAM")) ? [a.organizationUnitId] : []);
  return { OR: [{ ownerId: context.actorId }, ...(units.length ? [{ organizationUnitId: { in: [...new Set(units)] } }] : [])] };
}
function record(value: Prisma.ContractGetPayload<{ include: typeof include }>): ContractRecord {
  const latest = value.versions[0]; if (!latest) throw new Error("Contract version history is incomplete.");
  return { id: value.id, contractNo: value.contractNo, customerId: value.customerId, ownerId: value.ownerId, version: value.version, statusCode: value.statusCode, terminal: value.status.terminal, latestVersionId: latest.id, cleanSignatureParties: [...new Set(value.signatures.map((s) => s.partyCode))] };
}
function itemData(items: Array<ContractItemInput & { lineContractValue: string }>) { return items.map((item) => ({ ...item, productId: item.productId ?? null, description: item.description ?? null, solutionInstallationSiteId: item.solutionInstallationSiteId ?? null, serviceLocation: item.serviceLocation ?? null, bandwidth: item.bandwidth ?? null, sla: item.sla ?? null, supportLevel: item.supportLevel ?? null })); }

export class PrismaContractRepository implements ContractRepository<Tx> {
  constructor(private readonly client: PrismaClient) {}
  transaction<T>(work: (tx: Tx) => Promise<T>) { return this.client.$transaction(work); }
  async findAcceptedQuoteVersion(id: string, context: AuthorizationContext, tx: Tx) {
    const value = await tx.quoteVersion.findFirst({ where: { id, status: "ACCEPTED", quote: { opportunity: buildOpportunityScopeWhere(context) } }, include: { quote: { select: { id: true, customerId: true, opportunityId: true, proposalId: true } }, items: true } });
    if (!value) return null;
    return { quoteId: value.quote.id, quoteVersionId: value.id, status: value.status, customerId: value.quote.customerId, opportunityId: value.quote.opportunityId, proposalId: value.quote.proposalId, currency: value.currency, sourceSnapshot: { quoteVersionNumber: value.versionNumber, acceptedAt: value.acceptedAt?.toISOString() ?? null, total: value.total.toString(), items: value.items.map((i) => ({ productId: i.productId, productCode: i.productCode, productName: i.productName, quantity: i.quantity.toString(), unitPrice: i.unitPrice.toString(), lineTotal: i.lineTotal.toString() })) } };
  }
  async typeIsActive(code: string, tx: Tx) { return Boolean(await tx.contractTypeDefinition.findFirst({ where: { code, active: true }, select: { code: true } })); }
  async findInitialStatus(tx: Tx) { return (await tx.contractStatusDefinition.findFirst({ where: { active: true, terminal: false }, orderBy: { sortOrder: "asc" }, select: { code: true } }))?.code ?? null; }
  async nextNumber(now: Date, tx: Tx) { const seq = await tx.contractNumberSequence.upsert({ where: { id: "CONTRACT" }, create: { id: "CONTRACT", nextValue: 1 }, update: { nextValue: { increment: 1 } } }); const year = new Intl.DateTimeFormat("en-US", { year: "numeric", timeZone: "Asia/Bangkok" }).format(now); return `CT-${year}-${String(seq.nextValue).padStart(7, "0")}`; }
  async create(input: Parameters<ContractRepository<Tx>["create"]>[0], tx: Tx) {
    const f = input.financials, d = input.draft;
    const created = await tx.contract.create({ data: { contractNo: input.contractNo, name: d.name, contractTypeCode: d.contractTypeCode, statusCode: input.statusCode, customerId: input.source.customerId, customerContactId: d.customerContactId ?? null, ownerId: input.actorId, quoteId: input.source.quoteId, quoteVersionId: input.source.quoteVersionId, opportunityId: input.source.opportunityId, proposalId: input.source.proposalId, currency: input.source.currency, startDate: d.startDate ? new Date(d.startDate) : null, endDate: d.endDate ? new Date(d.endDate) : null, totalContractValue: f.totalContractValue, monthlyRecurringRevenue: f.monthlyRecurringRevenue, oneTimeRevenue: f.oneTimeRevenue, versions: { create: { versionNumber: 1, statusCode: input.statusCode, name: d.name, currency: input.source.currency, startDate: d.startDate ? new Date(d.startDate) : null, endDate: d.endDate ? new Date(d.endDate) : null, paymentTerm: d.paymentTerm ?? null, billingCycle: d.billingCycle ?? null, taxRate: d.taxRate, subtotal: f.subtotal, discountAmount: f.discountAmount, taxAmount: f.taxAmount, totalWithTax: f.totalWithTax, totalContractValue: f.totalContractValue, monthlyRecurringRevenue: f.monthlyRecurringRevenue, oneTimeRevenue: f.oneTimeRevenue, annualRecurringRevenue: f.annualRecurringRevenue, terms: d.terms ?? null, remarks: d.remarks ?? null, sourceSnapshot: input.source.sourceSnapshot as Prisma.InputJsonValue, createdById: input.actorId, items: { create: itemData(f.items) } } } }, include });
    return record(created);
  }
  async find(id: string, context: AuthorizationContext, tx: Tx) { const value = await tx.contract.findFirst({ where: { id, deletedAt: null, ...scope(context) }, include }); return value ? record(value) : null; }
  async loadCurrentDraft(contractId: string, context: AuthorizationContext, tx: Tx): Promise<ContractEditInput | null> {
    const value = await tx.contract.findFirst({ where: { id: contractId, deletedAt: null, ...scope(context) }, include: { versions: { orderBy: { versionNumber: "desc" }, take: 1, include: { items: { orderBy: { sortOrder: "asc" } } } } } }); const v = value?.versions[0]; if (!value || !v) return null;
    return { expectedVersion: value.version, changeReason: "Status transition", name: v.name, customerContactId: value.customerContactId, startDate: v.startDate?.toISOString() ?? null, endDate: v.endDate?.toISOString() ?? null, paymentTerm: v.paymentTerm, billingCycle: v.billingCycle, taxRate: v.taxRate.toString(), terms: v.terms, remarks: v.remarks, items: v.items.map((i) => ({ productId: i.productId, productCode: i.productCode, serviceName: i.serviceName, description: i.description, quantity: i.quantity.toString(), unit: i.unit, monthlyCharge: i.monthlyCharge.toString(), oneTimeCharge: i.oneTimeCharge.toString(), discountAmount: i.discountAmount.toString(), durationMonths: i.durationMonths, installationRequired: i.installationRequired, solutionInstallationSiteId: i.solutionInstallationSiteId, serviceLocation: i.serviceLocation, bandwidth: i.bandwidth, sla: i.sla, supportLevel: i.supportLevel, sortOrder: i.sortOrder })) };
  }
  async createVersion(input: Parameters<ContractRepository<Tx>["createVersion"]>[0], tx: Tx) { const f=input.financials,d=input.draft; const changed=await tx.contract.updateMany({where:{id:input.contract.id,version:input.expectedVersion,deletedAt:null},data:{version:{increment:1},name:d.name,statusCode:input.statusCode,startDate:d.startDate?new Date(d.startDate):null,endDate:d.endDate?new Date(d.endDate):null,totalContractValue:f.totalContractValue,monthlyRecurringRevenue:f.monthlyRecurringRevenue,oneTimeRevenue:f.oneTimeRevenue,effectiveAt:input.statusCode==="EFFECTIVE"?new Date():undefined}}); if(!changed.count)return null; const previous=await tx.contractVersion.findUniqueOrThrow({where:{id:input.contract.latestVersionId},select:{currency:true,sourceSnapshot:true}}); await tx.contractVersion.create({data:{contractId:input.contract.id,versionNumber:input.expectedVersion+1,statusCode:input.statusCode,name:d.name,currency:previous.currency,startDate:d.startDate?new Date(d.startDate):null,endDate:d.endDate?new Date(d.endDate):null,paymentTerm:d.paymentTerm??null,billingCycle:d.billingCycle??null,taxRate:d.taxRate,subtotal:f.subtotal,discountAmount:f.discountAmount,taxAmount:f.taxAmount,totalWithTax:f.totalWithTax,totalContractValue:f.totalContractValue,monthlyRecurringRevenue:f.monthlyRecurringRevenue,oneTimeRevenue:f.oneTimeRevenue,annualRecurringRevenue:f.annualRecurringRevenue,terms:d.terms??null,remarks:d.remarks??null,sourceSnapshot:(input.sourceSnapshot??previous.sourceSnapshot) as Prisma.InputJsonValue,changeReason:d.changeReason,amendmentId:input.amendmentId,createdById:input.actorId,items:{create:itemData(f.items)}}}); const current=await tx.contract.findUniqueOrThrow({where:{id:input.contract.id},include}); return record(current); }
  async createAmendment(input:Parameters<ContractRepository<Tx>["createAmendment"]>[0],tx:Tx){const count=await tx.contractAmendment.count({where:{contractId:input.contract.id}});return tx.contractAmendment.create({data:{contractId:input.contract.id,amendmentNo:`AMD-${String(count+1).padStart(3,"0")}`,amendmentTypeCode:input.amendmentTypeCode,status:"IN_REVIEW",reason:input.reason,sourceVersionNumber:input.contract.version,requestedById:input.actorId}});}
  async completeAmendment(id:string,resultingVersionNumber:number,tx:Tx){await tx.contractAmendment.update({where:{id},data:{resultingVersionNumber}});}
  async findTransition(from:string,to:string,tx:Tx){const edge=await tx.contractStatusTransition.findFirst({where:{fromStatusCode:from,toStatusCode:to,active:true}});return edge?{requiredPermission:edge.requiredPermission,makerChecker:edge.makerChecker,requiredSignatureParties:Array.isArray(edge.requiredSignatureParties)?edge.requiredSignatureParties.filter((v):v is string=>typeof v==="string"):[]}:null;}
  statusIsActive(code:string,tx:Tx){return tx.contractStatusDefinition.findFirst({where:{code,active:true},select:{terminal:true}});}
  async actorHasPermission(actorId:string,permission:string,tx:Tx){const roles=await tx.userRoleAssignment.findMany({where:{userId:actorId,active:true},select:{roleCode:true}});return Boolean(await tx.rolePermissionGrant.findFirst({where:{roleCode:{in:roles.map(r=>r.roleCode)},permissionCode:permission}}));}
  async createSignature(input:Parameters<ContractRepository<Tx>["createSignature"]>[0],tx:Tx){const doc=await tx.contractDocumentVersion.findFirst({where:{id:input.documentVersionId,malwareScanStatus:"CLEAN",document:{contractId:input.contract.id}}});if(!doc)return false;await tx.contractSignature.create({data:{contractId:input.contract.id,contractVersionId:input.contract.latestVersionId,partyCode:input.partyCode,methodCode:"MANUAL_UPLOAD",status:"VERIFIED",documentVersionId:doc.id,signedByName:input.signedByName,signedAt:input.signedAt,verifiedById:input.actorId}});return true;}
  async createServiceOrder(input:Parameters<ContractRepository<Tx>["createServiceOrder"]>[0],tx:Tx){const seq=await tx.contractNumberSequence.upsert({where:{id:"SERVICE_ORDER"},create:{id:"SERVICE_ORDER",nextValue:1},update:{nextValue:{increment:1}}});return tx.contractServiceOrder.create({data:{contractId:input.contract.id,contractVersionId:input.contract.latestVersionId,orderNo:`SO-${new Intl.DateTimeFormat("en-US",{year:"numeric",timeZone:"Asia/Bangkok"}).format(input.now)}-${String(seq.nextValue).padStart(7,"0")}`,status:"DRAFT",createdById:input.actorId,prefillSnapshot:{contractNo:input.contract.contractNo,contractVersion:input.contract.version,customerId:input.contract.customerId}}});}
}
