import { ActivityType, LeadSource, LeadStatus, LeadTemperature, PrismaClient, ProspectHeatLevel, ProspectSource, ProspectStatus, Role } from "@prisma/client";
import { hash } from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const email = process.env.SEED_ADMIN_EMAIL;
  const password = process.env.SEED_ADMIN_PASSWORD;
  const demoMode = process.env.SEED_DEMO_DATA === "1";
  let admin;
  if (email && password) {
    admin = await prisma.user.upsert({
      where: { email },
      update: { role: Role.ADMIN },
      create: { email, name: "ผู้ดูแลระบบ NTOP", passwordHash: await hash(password, 12), role: Role.ADMIN },
    });
  } else if (demoMode) {
    admin = await prisma.user.findFirst({ where: { role: Role.ADMIN, active: true }, orderBy: { createdAt: "asc" } });
    if (!admin) throw new Error("No active ADMIN exists; set SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD.");
  } else {
    throw new Error("Set SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD before seeding.");
  }
  const surveyCategoryCodes = new Set(["BROADBAND_INTERNET","FIBER_BROADBAND","DEDICATED_INTERNET","LEASED_LINE","MPLS","IP_VPN","SD_WAN","METRO_ETHERNET","DOMESTIC_DATA_NETWORK","INTERNATIONAL_DATA_NETWORK","DATA_CENTER_CONNECTIVITY","CLOUD_CONNECTIVITY"]);
  const categoryNames:Record<string,string>={BROADBAND_INTERNET:"Broadband Internet",FIBER_BROADBAND:"Fiber Broadband",DEDICATED_INTERNET:"Dedicated Internet Access",LEASED_LINE:"Leased Line",MPLS:"MPLS",IP_VPN:"IP VPN",SD_WAN:"SD-WAN",METRO_ETHERNET:"Metro Ethernet",DOMESTIC_DATA_NETWORK:"Domestic Data Network",INTERNATIONAL_DATA_NETWORK:"International Data Network",CLOUD_CONNECTIVITY:"Cloud Connectivity",DATA_CENTER_CONNECTIVITY:"Data Center Connectivity",CLOUD:"Cloud",CYBERSECURITY:"Cybersecurity",MANAGED_SERVICE:"Managed Service",VOICE:"Voice",MOBILE:"Mobile",IOT:"IoT",PROFESSIONAL_SERVICE:"Professional Service",DIGITAL_PLATFORM:"Digital Platform",DATA_AI:"Data and AI",OTHER:"Other"};
  let categoryOrder=0;
  for(const[code,name]of Object.entries(categoryNames)){const requires=surveyCategoryCodes.has(code);await prisma.serviceCategoryConfig.upsert({where:{code},update:{name,requiresSiteSurvey:requires,requiresBoq:requires,requiresPhysicalInstallation:requires,active:true,displayOrder:categoryOrder},create:{code,name,requiresSiteSurvey:requires,requiresBoq:requires,requiresPhysicalInstallation:requires,displayOrder:categoryOrder}});categoryOrder+=10;}
  const boqSections=["NETWORK_EQUIPMENT","CUSTOMER_PREMISE_EQUIPMENT","FIBER_CABLE","ACCESSORIES","RACK_POWER","CIVIL_WORK","INSTALLATION_LABOR","CONFIGURATION","TESTING_COMMISSIONING","PROFESSIONAL_SERVICE","PROJECT_MANAGEMENT","DOCUMENTATION","TRAINING","ONE_TIME_SERVICE_CHARGE","MONTHLY_RECURRING_CHARGE","ANNUAL_RECURRING_CHARGE","OTHER"];
  for(const[displayOrder,code]of boqSections.entries())await prisma.boqSection.upsert({where:{code},update:{name:code.split("_").map(v=>v[0]+v.slice(1).toLowerCase()).join(" "),active:true,displayOrder},create:{code,name:code.split("_").map(v=>v[0]+v.slice(1).toLowerCase()).join(" "),displayOrder}});
  const solutionStatuses=["DRAFT","REQUIREMENTS_REVIEW","SITE_SURVEY_REQUIRED","SITE_SURVEY_REQUESTED","SITE_SURVEY_SCHEDULED","SITE_SURVEY_IN_PROGRESS","SITE_SURVEY_COMPLETED","SOLUTION_IN_DESIGN","BOQ_PREPARATION","TECHNICAL_REVIEW","COMMERCIAL_REVIEW","REVISION_REQUIRED","APPROVED","REJECTED","CANCELLED","SUPERSEDED"];
  const solutionRequired:Record<string,string[]>={REQUIREMENTS_REVIEW:["opportunityId","solutionDesignName","salesOwnerId","preSalesOwnerId","customerRequirements","services"],SITE_SURVEY_REQUIRED:["sites"],SITE_SURVEY_REQUESTED:["sites"],SOLUTION_IN_DESIGN:["approvedSurvey"],BOQ_PREPARATION:["components"],TECHNICAL_REVIEW:["boq"],APPROVED:["boq"]};
  for(const[displayOrder,code]of solutionStatuses.entries())await prisma.solutionStatusDefinition.upsert({where:{entityType_code:{entityType:"SOLUTION_DESIGN",code}},update:{name:code.replaceAll("_"," "),displayOrder,requiredFields:solutionRequired[code]??[],active:true,closed:["APPROVED","REJECTED","CANCELLED","SUPERSEDED"].includes(code)},create:{entityType:"SOLUTION_DESIGN",code,name:code.replaceAll("_"," "),displayOrder,requiredFields:solutionRequired[code]??[],requiredChecklistItems:[],requiredApprovals:[],closed:["APPROVED","REJECTED","CANCELLED","SUPERSEDED"].includes(code)}});
  const surveyStatuses=["DRAFT","PENDING_INFORMATION","READY_TO_SUBMIT","SUBMITTED","ACKNOWLEDGED","ASSIGNED","SCHEDULED","IN_PROGRESS","COMPLETED","RESULT_SUBMITTED","RESULT_UNDER_REVIEW","RESULT_APPROVED","RETURNED_FOR_REVISION","CANCELLED","FAILED_INTEGRATION"];
  for(const[displayOrder,code]of surveyStatuses.entries())await prisma.solutionStatusDefinition.upsert({where:{entityType_code:{entityType:"SITE_SURVEY",code}},update:{name:code.replaceAll("_"," "),displayOrder,requiredFields:[],active:true,closed:["RESULT_APPROVED","CANCELLED"].includes(code)},create:{entityType:"SITE_SURVEY",code,name:code.replaceAll("_"," "),displayOrder,requiredFields:[],requiredChecklistItems:[],requiredApprovals:[],closed:["RESULT_APPROVED","CANCELLED"].includes(code)}});
  const boqStatuses=["DRAFT","IN_PREPARATION","PENDING_TECHNICAL_REVIEW","PENDING_COMMERCIAL_REVIEW","REVISION_REQUIRED","APPROVED","REJECTED","SUPERSEDED","CANCELLED"];
  for(const[displayOrder,code]of boqStatuses.entries())await prisma.solutionStatusDefinition.upsert({where:{entityType_code:{entityType:"BOQ",code}},update:{name:code.replaceAll("_"," "),displayOrder,requiredFields:[],active:true,closed:["APPROVED","REJECTED","SUPERSEDED","CANCELLED"].includes(code)},create:{entityType:"BOQ",code,name:code.replaceAll("_"," "),displayOrder,requiredFields:[],requiredChecklistItems:[],requiredApprovals:[],closed:["APPROVED","REJECTED","SUPERSEDED","CANCELLED"].includes(code)}});
  const solutionTransitions=[["DRAFT","REQUIREMENTS_REVIEW"],["REQUIREMENTS_REVIEW","SITE_SURVEY_REQUIRED"],["REQUIREMENTS_REVIEW","SOLUTION_IN_DESIGN"],["SITE_SURVEY_REQUIRED","SITE_SURVEY_REQUESTED"],["SITE_SURVEY_COMPLETED","SOLUTION_IN_DESIGN"],["SOLUTION_IN_DESIGN","BOQ_PREPARATION"],["BOQ_PREPARATION","TECHNICAL_REVIEW"],["TECHNICAL_REVIEW","COMMERCIAL_REVIEW"],["COMMERCIAL_REVIEW","APPROVED"],["TECHNICAL_REVIEW","REVISION_REQUIRED"],["COMMERCIAL_REVIEW","REVISION_REQUIRED"],["TECHNICAL_REVIEW","REJECTED"],["COMMERCIAL_REVIEW","REJECTED"],["REVISION_REQUIRED","SOLUTION_IN_DESIGN"]];
  const surveyTransitions=[["DRAFT","READY_TO_SUBMIT"],["DRAFT","SUBMITTED"],["READY_TO_SUBMIT","SUBMITTED"],["SUBMITTED","ASSIGNED"],["ASSIGNED","SCHEDULED"],["SCHEDULED","IN_PROGRESS"],["IN_PROGRESS","RESULT_SUBMITTED"],["RESULT_SUBMITTED","RESULT_APPROVED"],["RESULT_SUBMITTED","RETURNED_FOR_REVISION"],["RESULT_SUBMITTED","CANCELLED"],["RETURNED_FOR_REVISION","IN_PROGRESS"],["RETURNED_FOR_REVISION","RESULT_SUBMITTED"]];
  const boqTransitions=[["DRAFT","IN_PREPARATION"],["DRAFT","PENDING_TECHNICAL_REVIEW"],["IN_PREPARATION","PENDING_TECHNICAL_REVIEW"],["PENDING_TECHNICAL_REVIEW","PENDING_COMMERCIAL_REVIEW"],["PENDING_TECHNICAL_REVIEW","REVISION_REQUIRED"],["PENDING_COMMERCIAL_REVIEW","APPROVED"],["PENDING_COMMERCIAL_REVIEW","REVISION_REQUIRED"],["PENDING_TECHNICAL_REVIEW","REJECTED"],["PENDING_COMMERCIAL_REVIEW","REJECTED"],["REVISION_REQUIRED","PENDING_TECHNICAL_REVIEW"]];
  for(const[entityType,transitions]of [["SOLUTION_DESIGN",solutionTransitions],["SITE_SURVEY",surveyTransitions],["BOQ",boqTransitions]] as const)for(const[fromStatusCode,toStatusCode]of transitions)await prisma.solutionStatusTransition.upsert({where:{entityType_fromStatusCode_toStatusCode:{entityType,fromStatusCode,toStatusCode}},update:{active:true},create:{entityType,fromStatusCode,toStatusCode}});
  const presalesPermissionMatrix:Record<string,string[]>={KAM:["solution-design.view","solution-design.manage","site-survey.view","site-survey.request","boq.view"],PRESALES:["solution-design.view","solution-design.manage","solution-design.submit","site-survey.view","site-survey.request","site-survey.perform","boq.view","boq.manage","boq.cost.view"],SOLUTION_ARCHITECT:["solution-design.view","solution-design.manage","solution-design.submit","solution-design.technical.approve","site-survey.view","site-survey.coordinate","site-survey.result.approve","boq.view","boq.manage","boq.cost.view"],COVERAGE:["solution-design.view","site-survey.view","site-survey.coordinate","site-survey.perform"],PRICING_APPROVER:["solution-design.view","solution-design.commercial.approve","boq.view","boq.cost.view","boq.approve"]};
  for(const[roleCode,codes]of Object.entries(presalesPermissionMatrix))for(const permissionCode of codes)await prisma.rolePermissionGrant.upsert({where:{roleCode_permissionCode:{roleCode,permissionCode}},update:{},create:{roleCode,permissionCode}});
  const proposalApprovalPermissions:Record<string,string[]>={ADMIN:["proposal.review.manager","proposal.approve.director"],TEAM_MANAGER:["proposal.review.manager"],SALES_DIRECTOR:["proposal.approve.director"]};
  for(const[roleCode,codes]of Object.entries(proposalApprovalPermissions))for(const permissionCode of codes)await prisma.rolePermissionGrant.upsert({where:{roleCode_permissionCode:{roleCode,permissionCode}},update:{},create:{roleCode,permissionCode}});
  const proposalSections = [
    ["EXECUTIVE_SUMMARY","Executive Summary"],["CUSTOMER_CHALLENGES","Customer Challenges"],["BUSINESS_OBJECTIVES","Business Objectives"],["PROPOSED_SOLUTION","Proposed Solution"],["SOLUTION_BENEFITS","Solution Benefits"],["IMPLEMENTATION_PLAN","Implementation Plan"],["TIMELINE","Timeline"],["PROJECT_SCOPE","Project Scope"],["DELIVERABLES","Deliverables"],["ASSUMPTIONS","Assumptions"],["SUPPORT","Support"],["PRICING_SUMMARY","Pricing Summary"],["TERMS_AND_CONDITIONS","Terms & Conditions"],["NEXT_STEPS","Next Steps"],
  ] as const;
  const proposalTemplates = [["BROADBAND","Broadband"],["INTERNET_LEASE_LINE","Internet Lease Line"],["MPLS","MPLS"],["CLOUD","Cloud"],["MANAGED_SERVICE","Managed Service"],["CYBER_SECURITY","Cyber Security"],["DATA_CENTER","Data Center"],["AI_SOLUTION","AI Solution"],["IOT","IoT"]] as const;
  for (const [code,name] of proposalTemplates) {
    const template=await prisma.proposalTemplate.upsert({where:{code},update:{name,category:code,active:true},create:{code,name,category:code,createdById:admin.id}});
    let version=await prisma.proposalTemplateVersion.findUnique({where:{templateId_version:{templateId:template.id,version:1}}});
    if(!version)version=await prisma.proposalTemplateVersion.create({data:{templateId:template.id,version:1,createdById:admin.id,terms:"Commercial and legal terms require authorized review before sending.",footer:"NT Enterprise Sales",sections:{create:proposalSections.map(([sectionCode,title],sortOrder)=>({sectionCode,title,sortOrder,defaultContent:"",contentType:"RICH_TEXT"}))}}});
    if(template.activeVersionId!==version.id)await prisma.proposalTemplate.update({where:{id:template.id},data:{activeVersionId:version.id}});
  }
  const contractTypes = [["INTERNET_SERVICE","Internet Service"],["LEASED_LINE","Leased Line"],["MPLS","MPLS"],["CLOUD","Cloud"],["MANAGED_SERVICE","Managed Service"],["CYBER_SECURITY","Cyber Security"],["DATA_CENTER","Data Center"],["AI_SOLUTION","AI Solution"],["IOT","IoT"],["MASTER_SERVICE_AGREEMENT","Master Service Agreement"],["STATEMENT_OF_WORK","Statement of Work"],["MAINTENANCE","Maintenance"],["OTHER","Other"]] as const;
  for(const[code,name]of contractTypes)await prisma.contractTypeDefinition.upsert({where:{code},update:{name,active:true},create:{code,name}});
  const contractStatuses = [["DRAFT","Draft","OPEN",false],["INTERNAL_REVIEW","Internal Review","REVIEW",false],["LEGAL_REVIEW","Legal Review","REVIEW",false],["CUSTOMER_REVIEW","Customer Review","REVIEW",false],["REVISION_REQUIRED","Revision Required","OPEN",false],["PENDING_APPROVAL","Pending Approval","APPROVAL",false],["CUSTOMER_SIGN_PENDING","Customer Signature Pending","SIGNATURE",false],["NT_SIGN_PENDING","NT Signature Pending","SIGNATURE",false],["EFFECTIVE","Effective","ACTIVE",false],["READY_FOR_SERVICE_ORDER","Ready for Service Order","ACTIVE",false],["COMPLETED","Completed","CLOSED",true],["CANCELLED","Cancelled","CLOSED",true],["EXPIRED","Expired","CLOSED",true]] as const;
  for(const[sortOrder,[code,label,reportingCategory,terminal]]of contractStatuses.entries())await prisma.contractStatusDefinition.upsert({where:{code},update:{label,sortOrder,reportingCategory,terminal,active:true},create:{code,label,sortOrder,reportingCategory,terminal}});
  const contractTransitions = [["DRAFT","INTERNAL_REVIEW",null,false,[]],["INTERNAL_REVIEW","LEGAL_REVIEW","contract.review.manager",true,[]],["LEGAL_REVIEW","CUSTOMER_REVIEW","contract.review.legal",true,[]],["CUSTOMER_REVIEW","REVISION_REQUIRED","contract.manage",false,[]],["REVISION_REQUIRED","INTERNAL_REVIEW","contract.manage",false,[]],["CUSTOMER_REVIEW","PENDING_APPROVAL","contract.review.manager",true,[]],["PENDING_APPROVAL","CUSTOMER_SIGN_PENDING","contract.approve",true,[]],["CUSTOMER_SIGN_PENDING","NT_SIGN_PENDING","contract.signature.manage",false,["CUSTOMER"]],["NT_SIGN_PENDING","EFFECTIVE","contract.signature.manage",true,["CUSTOMER","NT"]],["EFFECTIVE","READY_FOR_SERVICE_ORDER","contract.service-order.create",false,["CUSTOMER","NT"]],["READY_FOR_SERVICE_ORDER","COMPLETED","contract.manage",true,[]]] as const;
  for(const[fromStatusCode,toStatusCode,requiredPermission,makerChecker,requiredSignatureParties]of contractTransitions)await prisma.contractStatusTransition.upsert({where:{fromStatusCode_toStatusCode:{fromStatusCode,toStatusCode}},update:{requiredPermission,makerChecker,requiredSignatureParties:[...requiredSignatureParties],active:true},create:{fromStatusCode,toStatusCode,requiredPermission,makerChecker,requiredSignatureParties:[...requiredSignatureParties]}});
  const contractPermissionMatrix:Record<string,string[]>={ADMIN:["contract.view","contract.manage","contract.review.manager","contract.review.legal","contract.approve","contract.signature.manage","contract.service-order.create"],KAM:["contract.view","contract.manage","contract.signature.manage","contract.service-order.create"],TEAM_MANAGER:["contract.view","contract.review.manager"],LEGAL:["contract.view","contract.review.legal"],SALES_DIRECTOR:["contract.view","contract.approve"]};
  for(const[roleCode,codes]of Object.entries(contractPermissionMatrix))for(const permissionCode of codes)await prisma.rolePermissionGrant.upsert({where:{roleCode_permissionCode:{roleCode,permissionCode}},update:{},create:{roleCode,permissionCode}});
  if (!demoMode) return;
  const demoPassword = process.env.SEED_DEMO_PASSWORD;
  if (!demoPassword || demoPassword.length < 12) throw new Error("Set SEED_DEMO_PASSWORD to 12+ characters when SEED_DEMO_DATA=1.");
  const passwordHash = await hash(demoPassword, 12);
  const unit = await prisma.organizationUnit.upsert({ where: { code: "DEMO-ENTERPRISE-SALES" }, update: { active: true }, create: { code: "DEMO-ENTERPRISE-SALES", name: "ทีมขายองค์กร (ข้อมูลทดสอบ)" } });
  const people = [
    ["sales1@example.test", "พนักงานขายทดสอบ 1", "KAM", "SELF"],
    ["sales2@example.test", "พนักงานขายทดสอบ 2", "KAM", "SELF"],
    ["sales3@example.test", "พนักงานขายทดสอบ 3", "KAM", "SELF"],
    ["manager@example.test", "ผู้จัดการฝ่ายขายทดสอบ", "TEAM_MANAGER", "TEAM"],
    ["marketing@example.test", "การตลาดทดสอบ", "MARKETING", "ORG_UNIT"],
    ["architect@example.test", "Solution Architect ทดสอบ", "SOLUTION_ARCHITECT", "ORG_UNIT"],
    ["presales@example.test", "Pre-Sales Engineer ทดสอบ", "PRESALES", "ORG_UNIT"],
    ["survey@example.test", "Survey Engineer ทดสอบ", "COVERAGE", "ASSIGNED_TASK"],
    ["pricing@example.test", "Commercial Approver ทดสอบ", "PRICING_APPROVER", "ORG_UNIT"],
  ] as const;
  const users = [];
  for (const [userEmail, name, roleCode, scopeCode] of people) {
    const user = await prisma.user.upsert({ where: { email: userEmail }, update: { name, active: true }, create: { email: userEmail, name, passwordHash, role: Role.SALES } });
    users.push(user);
    const existing = await prisma.userRoleAssignment.findFirst({ where: { userId: user.id, roleCode, scopeCode, organizationUnitId: unit.id, active: true } });
    if (!existing) await prisma.userRoleAssignment.create({ data: { userId: user.id, roleCode, scopeCode, organizationUnitId: unit.id, effectiveFrom: new Date("2026-01-01T00:00:00Z") } });
  }
  const adminAssignment = await prisma.userRoleAssignment.findFirst({ where: { userId: admin.id, roleCode: "ADMIN", scopeCode: "ENTERPRISE", active: true } });
  if (!adminAssignment) await prisma.userRoleAssignment.create({ data: { userId: admin.id, roleCode: "ADMIN", scopeCode: "ENTERPRISE", effectiveFrom: new Date("2026-01-01T00:00:00Z") } });
  const prospectPermissions = ["prospect.view","prospect.create","prospect.update","prospect.assign","prospect.convert","prospect.merge","prospect.archive","prospect.import","prospect.export","prospect.view_all"];
  const permissionMatrix:Record<string,string[]>={ADMIN:[...prospectPermissions,"prospect.soft_delete","prospect.view_deleted","prospect.restore","lead.archive","customer.lifecycle.manage"],SYSTEM_ADMIN:["prospect.view_deleted","prospect.restore","prospect.permanent_delete"],SALES_DIRECTOR:prospectPermissions,TEAM_MANAGER:[...prospectPermissions.filter(code=>code!=="prospect.view_all"),"prospect.soft_delete"],KAM:["prospect.view","prospect.create","prospect.update","prospect.convert","prospect.export"],MARKETING:["prospect.view","prospect.create","prospect.import","prospect.export"]};
  permissionMatrix.ADMIN.push("opportunity.probability.override");
  permissionMatrix.ADMIN.push("solution-design.view","solution-design.manage","solution-design.submit","solution-design.technical.approve","solution-design.commercial.approve","site-survey.view","site-survey.request","site-survey.coordinate","site-survey.perform","site-survey.result.approve","boq.view","boq.manage","boq.cost.view","boq.approve");
  permissionMatrix.KAM.push("solution-design.view","solution-design.manage","site-survey.view","site-survey.request","boq.view");
  permissionMatrix.PRESALES=["solution-design.view","solution-design.manage","solution-design.submit","site-survey.view","site-survey.request","site-survey.perform","boq.view","boq.manage","boq.cost.view"];
  permissionMatrix.SOLUTION_ARCHITECT=["solution-design.view","solution-design.manage","solution-design.submit","solution-design.technical.approve","site-survey.view","site-survey.coordinate","site-survey.result.approve","boq.view","boq.manage","boq.cost.view"];
  permissionMatrix.COVERAGE=["solution-design.view","site-survey.view","site-survey.coordinate","site-survey.perform"];
  permissionMatrix.PRICING_APPROVER=["solution-design.view","solution-design.commercial.approve","boq.view","boq.cost.view","boq.approve"];
  permissionMatrix.ADMIN.push("forecast.target.manage", "forecast.calendar.manage", "forecast.snapshot.create");
  permissionMatrix.SALES_DIRECTOR.push("opportunity.probability.override");
  permissionMatrix.SALES_DIRECTOR.push("forecast.target.manage", "forecast.snapshot.create");
  permissionMatrix.TEAM_MANAGER.push("opportunity.probability.override");
  permissionMatrix.TEAM_MANAGER.push("forecast.target.manage", "forecast.snapshot.create");
  for(const [roleCode,codes] of Object.entries(permissionMatrix))for(const permissionCode of codes)await prisma.rolePermissionGrant.upsert({where:{roleCode_permissionCode:{roleCode,permissionCode}},update:{},create:{roleCode,permissionCode}});
  const productSeeds=[
    {code:"NT-BB-1000",name:"NT Broadband Internet 1 Gbps",category:"Broadband",serviceCategoryCode:"BROADBAND_INTERNET",listPrice:"25000.0000",standardCost:"12000.0000",requiresSiteSurvey:true,requiresBoq:true,requiresPhysicalInstallation:true},
    {code:"NT-DIA-1000",name:"NT Dedicated Internet 1 Gbps",category:"Data Network",serviceCategoryCode:"DEDICATED_INTERNET",listPrice:"85000.0000",standardCost:"45000.0000",requiresSiteSurvey:true,requiresBoq:true,requiresPhysicalInstallation:true},
    {code:"NT-MPLS-100",name:"NT MPLS 100 Mbps",category:"Data Network",serviceCategoryCode:"MPLS",listPrice:"42000.0000",standardCost:"23000.0000",requiresSiteSurvey:true,requiresBoq:true,requiresPhysicalInstallation:true},
    {code:"NT-CLOUD-MANAGED",name:"NT Managed Cloud Service",category:"Cloud",serviceCategoryCode:"CLOUD",listPrice:"30000.0000",standardCost:"18000.0000",requiresSiteSurvey:false,requiresBoq:false,requiresPhysicalInstallation:false},
  ];
  for(const product of productSeeds)await prisma.product.upsert({where:{code:product.code},update:product,create:product});
  const industries=await Promise.all([["GOV","ภาครัฐ"],["FIN","การเงินและธนาคาร"],["MFG","การผลิต"],["RET","ค้าปลีก"],["HEALTH","สาธารณสุข"]].map(([code,name])=>prisma.industry.upsert({where:{code},update:{active:true},create:{code,name}})));
  const territories=await Promise.all([["BKK","กรุงเทพมหานคร","CENTRAL"],["NORTH","ภาคเหนือ","NORTH"],["NE","ภาคตะวันออกเฉียงเหนือ","NORTHEAST"],["SOUTH","ภาคใต้","SOUTH"]].map(([code,name,region])=>prisma.salesTerritory.upsert({where:{code},update:{active:true},create:{code,name,region}})));
  await prisma.prospectScoringRuleVersion.upsert({where:{version:1},update:{active:true},create:{version:1,active:true,createdById:admin.id,hotThreshold:75,warmThreshold:40,weights:{estimatedValue:15,companySize:8,branches:7,industryFit:8,contractTiming:8,contactFrequency:8,interest:10,budget:8,purchasePeriod:7,sourceQuality:6,aiScore:8,recency:4,completeness:3}}});
  const campaigns = await Promise.all([
    prisma.campaign.upsert({ where: { code: "DEMO-CLOUD-2026" }, update: { active: true }, create: { code: "DEMO-CLOUD-2026", name: "Cloud Enterprise Demo 2026", source: "MARKETING" } }),
    prisma.campaign.upsert({ where: { code: "DEMO-GOV-2026" }, update: { active: true }, create: { code: "DEMO-GOV-2026", name: "Government Digital Demo 2026", source: "EVENT" } }),
  ]);
  const statuses = [LeadStatus.NEW, LeadStatus.ASSIGNED, LeadStatus.CONTACTED, LeadStatus.NURTURING, LeadStatus.QUALIFIED, LeadStatus.DISQUALIFIED, LeadStatus.CONVERTED, LeadStatus.ARCHIVED];
  const temperatures = [LeadTemperature.HOT, LeadTemperature.WARM, LeadTemperature.COLD];
  for (let index = 0; index < 20; index += 1) {
    const owner = users[index % 3]; const status = statuses[index % statuses.length]; const temperature = temperatures[index % temperatures.length];
    await prisma.lead.upsert({
      where: { leadNumber: `DEMO-L-${String(index + 1).padStart(4, "0")}` },
      update: {},
      create: { leadNumber: `DEMO-L-${String(index + 1).padStart(4, "0")}`, company: index >= 18 ? "บริษัทตัวอย่างซ้ำ จำกัด" : `บริษัทตัวอย่าง ${index + 1} จำกัด`, contactName: `ผู้ติดต่อทดสอบ ${index + 1}`, contactEmail: `lead${index + 1}@example.test`, contactPhone: `080000${String(index + 1).padStart(4, "0")}`, source: index % 2 ? LeadSource.MARKETING_CAMPAIGN : LeadSource.WEBSITE, campaignId: campaigns[index % campaigns.length].id, status, temperature, score: temperature === LeadTemperature.HOT ? 80 : temperature === LeadTemperature.WARM ? 55 : 25, ownerId: owner.id, organizationUnitId: unit.id, recommendedProducts: "บริการทดสอบ NT", requirementSummary: status === LeadStatus.QUALIFIED ? "ความต้องการสมมติสำหรับทดสอบ conversion" : null, estimatedBudget: status === LeadStatus.QUALIFIED ? "1000000.0000" : null, nextFollowUpAt: index === 17 ? new Date("2026-01-01T02:00:00Z") : null },
    });
  }
  const prospectStatuses=[ProspectStatus.NEW,ProspectStatus.ASSIGNED,ProspectStatus.CONTACTED,ProspectStatus.INTERESTED,ProspectStatus.QUALIFYING,ProspectStatus.QUALIFIED,ProspectStatus.NOT_INTERESTED,ProspectStatus.UNREACHABLE,ProspectStatus.LOST,ProspectStatus.CONVERTED,ProspectStatus.ARCHIVED];
  const prospectSources=[ProspectSource.MANUAL,ProspectSource.WEBSITE,ProspectSource.LINE_OA,ProspectSource.CALL_CENTER,ProspectSource.EVENT,ProspectSource.PARTNER,ProspectSource.REFERRAL,ProspectSource.TENDER,ProspectSource.GOVERNMENT_PROJECT,ProspectSource.COMPANY_REGISTRY,ProspectSource.IMPORT];
  const provinces=["กรุงเทพมหานคร","เชียงใหม่","ขอนแก่น","สงขลา","ชลบุรี"],regions=["CENTRAL","NORTH","NORTHEAST","SOUTH","EAST"];
  for(let index=0;index<20;index+=1){const owner=users[index%3],status=prospectStatuses[index%prospectStatuses.length],heat=[ProspectHeatLevel.HOT,ProspectHeatLevel.WARM,ProspectHeatLevel.COLD][index%3],prospect=await prisma.prospect.upsert({where:{prospectCode:`DEMO-P-${String(index+1).padStart(4,"0")}`},update:{},create:{prospectCode:`DEMO-P-${String(index+1).padStart(4,"0")}`,companyName:`องค์กรเป้าหมายทดสอบ ${index+1}`,companyNameEnglish:`Demo Prospect ${index+1}`,normalizedCompanyName:`องค์กรเป้าหมายทดสอบ${index+1}`,normalizedCompanyEnglish:`demoprospect${index+1}`,taxId:`99999${String(index+1).padStart(8,"0")}`,industryId:industries[index%industries.length].id,province:provinces[index%provinces.length],region:regions[index%regions.length],salesTerritoryId:territories[index%territories.length].id,responsibleBusinessUnitId:unit.id,salesTeamId:unit.id,ownerId:owner.id,status,source:prospectSources[index%prospectSources.length],heatLevel:heat,calculatedScore:heat==="HOT"?82:heat==="WARM"?55:25,aiOpportunityScore:70+(index%25),aiConfidenceScore:65+(index%20),aiRiskScore:15+(index%40),estimatedOpportunityValue:`${(index+1)*250000}.0000`,expectedBudget:`${(index+1)*200000}.0000`,numberOfBranches:(index%8)+1,numberOfEmployees:(index+1)*40,businessPainPoints:"ข้อมูล pain point สังเคราะห์สำหรับทดสอบ",recommendedProducts:"NT Cloud, Cybersecurity, Managed Service",nextFollowUpAt:index%4===0?new Date("2026-07-01T02:00:00Z"):new Date("2026-08-01T02:00:00Z"),createdById:admin.id,updatedById:admin.id,contacts:{create:{name:`ผู้ติดต่อ Prospect ${index+1}`,position:"ผู้จัดการ",mobile:`081111${String(index+1).padStart(4,"0")}`,email:`prospect${index+1}@example.test`,preferredContactChannel:"MOBILE",isPrimary:true,createdById:admin.id,updatedById:admin.id}}}});if(!(await prisma.activity.count({where:{prospectId:prospect.id}})))await prisma.activity.create({data:{prospectId:prospect.id,ownerId:owner.id,type:index%2?ActivityType.PHONE_CALL:ActivityType.MEETING,subject:"กิจกรรมตัวอย่าง Prospect",description:"กิจกรรมสังเคราะห์สำหรับ Dashboard และ Timeline",activityAt:new Date("2026-07-10T03:00:00Z"),nextFollowUpAt:prospect.nextFollowUpAt}});}
}

main().finally(() => prisma.$disconnect());
