"use client";
import { useActionState, useState } from "react";
import { createLead } from "@/app/actions/lead";
import type { FormState } from "@/app/action-types";
import { LEAD_SOURCES } from "@/lib/constants";
import { FormField, Input, Textarea } from "./form-field";
import { FormNotice } from "./notice";

export function LeadCreateForm({customers}:{customers:Array<{id:string;name:string;taxId:string}>}){
  const [state,action,pending]=useActionState(createLead,{} as FormState); const key=useState(()=>crypto.randomUUID())[0];
  return <form action={action} className="card form-card"><div className="card-body"><input type="hidden" name="idempotencyKey" value={key}/><input type="hidden" name="status" value="NEW"/><input type="hidden" name="score" value="0"/><div className="form-section"><h2>ข้อมูล Lead</h2><p>กรอกเฉพาะข้อมูลที่ทราบ ระบบตรวจข้อมูลซ้ำก่อนสร้าง</p><div className="form-grid"><FormField label="บริษัท/หน่วยงาน" name="company" required error={state.errors?.company}><Input name="company" required error={!!state.errors?.company}/></FormField><FormField label="ชื่อผู้ติดต่อ" name="contactName" required error={state.errors?.contactName}><Input name="contactName" required error={!!state.errors?.contactName}/></FormField><FormField label="อีเมล" name="contactEmail" error={state.errors?.contactEmail}><Input name="contactEmail" type="email" error={!!state.errors?.contactEmail}/></FormField><FormField label="โทรศัพท์" name="contactPhone" error={state.errors?.contactPhone}><Input name="contactPhone" error={!!state.errors?.contactPhone}/></FormField><FormField label="แหล่งที่มา" name="source" required><select className="control" name="source" defaultValue="WEBSITE">{LEAD_SOURCES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></FormField><FormField label="Customer เดิม (ถ้ามี)" name="customerId"><select className="control" name="customerId" defaultValue=""><option value="">ยังไม่เชื่อม</option>{customers.map(item=><option key={item.id} value={item.id}>{item.name} ({item.taxId})</option>)}</select></FormField><div className="field full"><FormField label="สินค้า/บริการที่สนใจ" name="recommendedProducts" error={state.errors?.recommendedProducts}><Input name="recommendedProducts" error={!!state.errors?.recommendedProducts}/></FormField></div><div className="field full"><FormField label="สรุปความต้องการ" name="notes" error={state.errors?.notes}><Textarea name="notes" error={!!state.errors?.notes}/></FormField></div><div className="field full"><FormField label="เหตุผลยืนยันสร้างต่อเมื่อพบรายการซ้ำ" name="duplicateOverrideReason" help="เว้นว่างในครั้งแรก ระบบจะแจ้งจำนวนรายการที่อาจซ้ำ"><Textarea name="duplicateOverrideReason" minLength={5}/></FormField></div></div></div><FormNotice state={state}/><div className="actions"><button className="primary" disabled={pending}>{pending?"กำลังตรวจสอบและบันทึก…":"ตรวจสอบและสร้าง Lead"}</button></div></div></form>;
}
