"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Notice, type NoticeVariant } from "./notice";

type Collection="pain-points"|"requirements"|"stakeholders"|"competitors";
const priorities=["LOW","MEDIUM","HIGH","CRITICAL"];
const levels=["LOW","MEDIUM","HIGH"];
const text=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const nullable=(form:FormData,key:string)=>text(form,key)||null;

export function OpportunityRelatedForms({opportunityId}:{opportunityId:string}){
  const router=useRouter(),[message,setMessage]=useState<{text:string;variant:NoticeVariant}|null>(null);
  const submit=async(event:React.FormEvent<HTMLFormElement>,collection:Collection,body:(form:FormData)=>object)=>{event.preventDefault();setMessage(null);const form=new FormData(event.currentTarget),response=await fetch(`/api/v1/opportunities/${opportunityId}/${collection}`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify(body(form))}),result=await response.json();if(!response.ok){setMessage({text:result.error?.message??"บันทึกไม่สำเร็จ",variant:"error"});return;}event.currentTarget.reset();setMessage({text:"บันทึกข้อมูล Opportunity แล้ว",variant:"success"});router.refresh();};
  return <section className="related-create card"><div className="card-header"><div><strong>เพิ่มข้อมูลประกอบ Opportunity</strong><small>ข้อมูลนี้ใช้กับ Stage Gate, Health และกลยุทธ์การขาย</small></div></div><div className="card-body related-accordions">
    <details><summary>Pain Point <span>เพิ่มปัญหาและผลกระทบ</span></summary><form onSubmit={event=>submit(event,"pain-points",form=>({category:text(form,"category"),title:text(form,"title"),businessProblem:text(form,"businessProblem"),currentSituation:nullable(form,"currentSituation"),impact:nullable(form,"impact"),expectedOutcome:nullable(form,"expectedOutcome"),priority:text(form,"priority"),status:"OPEN",source:nullable(form,"source")}))}><label>หมวดหมู่<input className="control" name="category" required maxLength={100}/></label><label>หัวข้อ<input className="control" name="title" required maxLength={255}/></label><label className="full">Business problem<textarea className="control" name="businessProblem" required/></label><label>สถานการณ์ปัจจุบัน<textarea className="control" name="currentSituation"/></label><label>ผลกระทบ<textarea className="control" name="impact"/></label><label>ผลลัพธ์ที่คาดหวัง<textarea className="control" name="expectedOutcome"/></label><label>Priority<select className="control" name="priority" defaultValue="MEDIUM">{priorities.map(item=><option key={item}>{item}</option>)}</select></label><label>แหล่งข้อมูล<input className="control" name="source"/></label><button className="primary">เพิ่ม Pain Point</button></form></details>
    <details><summary>Requirement <span>เพิ่มเกณฑ์และ Feasibility</span></summary><form onSubmit={event=>submit(event,"requirements",form=>({requirementNumber:text(form,"requirementNumber"),title:text(form,"title"),description:text(form,"description"),requirementType:text(form,"requirementType"),priority:text(form,"priority"),mandatoryFlag:form.get("mandatoryFlag")==="on",acceptanceCriteria:nullable(form,"acceptanceCriteria"),sourceDocument:nullable(form,"sourceDocument"),status:"OPEN",assignedTeam:nullable(form,"assignedTeam"),feasibilityStatus:text(form,"feasibilityStatus"),solutionResponse:null,riskLevel:text(form,"riskLevel")}))}><label>Requirement No.<input className="control" name="requirementNumber" placeholder="REQ-001" required/></label><label>ประเภท<select className="control" name="requirementType"><option>BUSINESS</option><option>FUNCTIONAL</option><option>TECHNICAL</option><option>SECURITY</option><option>INTEGRATION</option><option>NETWORK</option><option>SLA</option><option>COMPLIANCE</option><option>COMMERCIAL</option><option>OTHER</option></select></label><label className="full">หัวข้อ<input className="control" name="title" required/></label><label className="full">รายละเอียด<textarea className="control" name="description" required/></label><label className="full">Acceptance criteria<textarea className="control" name="acceptanceCriteria"/></label><label>Priority<select className="control" name="priority" defaultValue="MEDIUM">{priorities.map(item=><option key={item}>{item}</option>)}</select></label><label>Risk<select className="control" name="riskLevel" defaultValue="MEDIUM">{priorities.map(item=><option key={item}>{item}</option>)}</select></label><label>Feasibility<select className="control" name="feasibilityStatus"><option>NOT_ASSESSED</option><option>FEASIBLE</option><option>PARTIAL</option><option>NOT_FEASIBLE</option></select></label><label>Assigned team<input className="control" name="assignedTeam"/></label><label>Source document<input className="control" name="sourceDocument"/></label><label className="checkbox-field"><input type="checkbox" name="mandatoryFlag"/> Mandatory requirement</label><button className="primary">เพิ่ม Requirement</button></form></details>
    <details><summary>Stakeholder <span>เพิ่มบทบาท Influence และ Support</span></summary><form onSubmit={event=>submit(event,"stakeholders",form=>({name:text(form,"name"),organization:nullable(form,"organization"),department:nullable(form,"department"),jobTitle:nullable(form,"jobTitle"),email:nullable(form,"email"),phone:nullable(form,"phone"),stakeholderRole:text(form,"stakeholderRole"),influenceLevel:text(form,"influenceLevel"),decisionPower:text(form,"decisionPower"),relationshipStrength:text(form,"relationshipStrength"),attitude:text(form,"attitude"),supportLevel:text(form,"supportLevel"),preferredCommunication:nullable(form,"preferredCommunication"),notes:nullable(form,"notes"),primaryContactFlag:form.get("primaryContactFlag")==="on",contactId:null}))}><label>ชื่อ<input className="control" name="name" required/></label><label>บทบาท<select className="control" name="stakeholderRole"><option>ECONOMIC_BUYER</option><option>DECISION_MAKER</option><option>TECHNICAL_BUYER</option><option>CHAMPION</option><option>PROCUREMENT</option><option>FINANCE</option><option>LEGAL</option><option>INFLUENCER</option><option>OTHER</option></select></label><label>องค์กร<input className="control" name="organization"/></label><label>ตำแหน่ง<input className="control" name="jobTitle"/></label><label>อีเมล<input className="control" name="email" type="email"/></label><label>โทรศัพท์<input className="control" name="phone"/></label><label>Influence<select className="control" name="influenceLevel">{levels.map(item=><option key={item}>{item}</option>)}</select></label><label>Decision power<select className="control" name="decisionPower">{levels.map(item=><option key={item}>{item}</option>)}</select></label><label>Relationship<select className="control" name="relationshipStrength">{levels.map(item=><option key={item}>{item}</option>)}</select></label><label>Support<select className="control" name="supportLevel"><option>OPPOSED</option><option>NEUTRAL</option><option>SUPPORTIVE</option><option>CHAMPION</option></select></label><label>Attitude<select className="control" name="attitude"><option>NEGATIVE</option><option>NEUTRAL</option><option>POSITIVE</option></select></label><label>ช่องทางที่ต้องการ<input className="control" name="preferredCommunication"/></label><label className="full">หมายเหตุ<textarea className="control" name="notes"/></label><label className="checkbox-field"><input type="checkbox" name="primaryContactFlag"/> ผู้ติดต่อหลัก</label><button className="primary">เพิ่ม Stakeholder</button></form></details>
    <details><summary>Competitor <span>เพิ่ม Threat และ Win Strategy</span></summary><form onSubmit={event=>submit(event,"competitors",form=>({competitorName:text(form,"competitorName"),incumbentFlag:form.get("incumbentFlag")==="on",estimatedPrice:nullable(form,"estimatedPrice"),strengths:nullable(form,"strengths"),weaknesses:nullable(form,"weaknesses"),relationshipLevel:text(form,"relationshipLevel"),threatLevel:text(form,"threatLevel"),likelySolution:nullable(form,"likelySolution"),winStrategy:nullable(form,"winStrategy"),differentiation:nullable(form,"differentiation"),notes:nullable(form,"notes")}))}><label>คู่แข่ง<input className="control" name="competitorName" required/></label><label>ราคาประมาณการ<input className="control" name="estimatedPrice" inputMode="decimal" pattern="\d+(\.\d{1,4})?"/></label><label>Threat<select className="control" name="threatLevel">{levels.map(item=><option key={item}>{item}</option>)}</select></label><label>Relationship<select className="control" name="relationshipLevel"><option>UNKNOWN</option>{levels.map(item=><option key={item}>{item}</option>)}</select></label><label>จุดแข็ง<textarea className="control" name="strengths"/></label><label>จุดอ่อน<textarea className="control" name="weaknesses"/></label><label className="full">Win strategy<textarea className="control" name="winStrategy"/></label><label className="full">Differentiation<textarea className="control" name="differentiation"/></label><label className="checkbox-field"><input type="checkbox" name="incumbentFlag"/> ผู้ให้บริการเดิม</label><button className="primary">เพิ่ม Competitor</button></form></details>
    {message&&<Notice variant={message.variant}>{message.text}</Notice>}
  </div></section>;
}
