"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { ProspectSource, ProspectStatus } from "@prisma/client";
import { useEffect, useState } from "react";
import { useForm, type Resolver } from "react-hook-form";
import { useRouter } from "next/navigation";
import { Notice } from "@/components/notice";
import { prospectCommandSchema, type ProspectCommand } from "@/lib/prospect/prospect-validation";

const sources=Object.values(ProspectSource),statuses=Object.values(ProspectStatus).filter(value=>value!=="CONVERTED"&&value!=="ARCHIVED");
export function ProspectForm({prospect}:{prospect?:Partial<ProspectCommand>&{id:string;version:number}}){const router=useRouter(),[message,setMessage]=useState(""),[duplicates,setDuplicates]=useState<Array<{id:string;prospectCode:string;companyName:string}>>([]);const {register,handleSubmit,watch,formState:{errors,isDirty,isSubmitting}}=useForm<ProspectCommand>({resolver:zodResolver(prospectCommandSchema) as Resolver<ProspectCommand>,defaultValues:prospect??{source:"MANUAL",status:"NEW",contact:{name:"",email:"",isPrimary:true}}});useEffect(()=>{if(!prospect){const subscription=watch(value=>localStorage.setItem("ntop-prospect-draft",JSON.stringify(value)));return()=>subscription.unsubscribe();}},[prospect,watch]);useEffect(()=>{const warning=(event:BeforeUnloadEvent)=>{if(isDirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",warning);return()=>window.removeEventListener("beforeunload",warning);},[isDirty]);const submit=handleSubmit(async values=>{setMessage("");setDuplicates([]);const response=await fetch(prospect?`/api/v1/prospects/${prospect.id}`:"/api/v1/prospects",{method:prospect?"PATCH":"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify(prospect?{...values,expectedVersion:prospect.version}:values)}),result=await response.json();if(response.status===409&&result.error?.code==="DUPLICATE_RESOLUTION_REQUIRED"){setDuplicates(result.error.data??[]);setMessage("พบ Prospect ที่อาจซ้ำ กรุณาเปิดรายการเดิมหรือระบุเหตุผลเพื่อสร้างต่อ");return;}if(!response.ok){setMessage(result.error?.message??"บันทึกไม่สำเร็จ");return;}localStorage.removeItem("ntop-prospect-draft");router.push(`/prospects/${result.data.id}`);router.refresh();});const field=(name:keyof ProspectCommand,label:string,type="text")=><label className="field"><span>{label}</span><input className="control" type={type} {...register(name as never)}/>{errors[name]&&<small className="error">{String(errors[name]?.message??"ข้อมูลไม่ถูกต้อง")}</small>}</label>;return <form className="card form-card" onSubmit={submit}><div className="card-body">
<section className="form-section"><h2>1. Company Information</h2><div className="form-grid">{field("companyName","ชื่อบริษัท/หน่วยงาน")}{field("companyNameEnglish","ชื่อภาษาอังกฤษ")}{field("taxId","เลขผู้เสียภาษี 13 หลัก")}{field("branchNumber","เลขสาขา")}{field("customerType","ประเภทลูกค้า")}{field("organizationType","ประเภทองค์กร")}{field("subIndustry","อุตสาหกรรมย่อย")}{field("companySize","ขนาดบริษัท")}<label className="field"><span>จำนวนพนักงาน</span><input className="control" type="number" min="0" {...register("numberOfEmployees",{valueAsNumber:true})}/></label>{field("website","เว็บไซต์","url")}</div></section>
<section className="form-section"><h2>2. Address and Territory</h2><div className="form-grid">{field("address","ที่อยู่")}{field("subDistrict","ตำบล/แขวง")}{field("district","อำเภอ/เขต")}{field("province","จังหวัด")}{field("postalCode","รหัสไปรษณีย์")}{field("region","ภูมิภาค")}</div></section>
<section className="form-section"><h2>3. Primary Contact</h2><div className="form-grid"><label className="field"><span>ชื่อผู้ติดต่อ</span><input className="control" {...register("contact.name")}/></label><label className="field"><span>ตำแหน่ง</span><input className="control" {...register("contact.position")}/></label><label className="field"><span>อีเมล</span><input className="control" type="email" {...register("contact.email")}/></label><label className="field"><span>โทรศัพท์</span><input className="control" {...register("contact.phone")}/></label><label className="field"><span>มือถือ</span><input className="control" {...register("contact.mobile")}/></label><label className="field"><span>LINE ID</span><input className="control" {...register("contact.lineId")}/></label></div></section>
<section className="form-section"><h2>4–6. Business, Providers and Opportunity</h2><div className="form-grid">{field("currentTelecomProvider","Telecom Provider")}{field("currentInternetProvider","Internet Provider")}{field("currentCloudProvider","Cloud Provider")}{field("currentSecurityProvider","Security Provider")}{field("expectedBudget","Expected Budget")}{field("estimatedOpportunityValue","Estimated Opportunity Value")}{field("expectedPurchasePeriod","Expected Purchase Period")}{field("currentContractEndDate","Contract End Date","date")}<label className="field full"><span>Business Pain Points</span><textarea className="control" {...register("businessPainPoints")}/></label><label className="field full"><span>Recommended Products</span><textarea className="control" {...register("recommendedProducts")}/></label></div></section>
<section className="form-section"><h2>7–9. Source, Ownership and Notes</h2><div className="form-grid"><label className="field"><span>Source</span><select className="control" {...register("source")}>{sources.map(value=><option key={value}>{value}</option>)}</select></label><label className="field"><span>Status</span><select className="control" {...register("status")}>{statuses.map(value=><option key={value}>{value}</option>)}</select></label>{field("sourceName","ชื่อแหล่งที่มา")}{field("referralName","ผู้แนะนำ")}<label className="field full"><span>Notes</span><textarea className="control" {...register("notes")}/></label><label className="field full"><span>เหตุผลสร้างต่อเมื่อพบข้อมูลซ้ำ</span><textarea className="control" {...register("duplicateOverrideReason")}/></label></div></section>
{duplicates.length>0&&<Notice variant="warning">{duplicates.map(item=><p key={item.id}><a className="link" href={`/prospects/${item.id}`}>{item.prospectCode} · {item.companyName}</a></p>)}</Notice>}{message&&<Notice variant={duplicates.length>0?"warning":"error"}>{message}</Notice>}<div className="actions"><button type="button" className="secondary" onClick={()=>router.back()}>ยกเลิก</button><button type="submit" className="primary" disabled={isSubmitting}>{isSubmitting?"กำลังบันทึก…":prospect?"บันทึกการแก้ไข":"สร้าง Prospect"}</button></div></div></form>}
