"use client";

import { Fragment, useActionState, useState } from "react";

import { createSolutionReferenceAction, updateSolutionReferenceAction } from "@/app/actions/solution-reference";
import type { FormState } from "@/app/action-types";
import { PageNumberNavigation } from "./page-number-navigation";
import { SortableTableHeader } from "./sortable-table-header";
import { FormNotice } from "./notice";

const groups=[["SOLUTION_CATEGORY","Solution Category"],["COMPONENT_TYPE","Component Type"],["RISK_CATEGORY","Risk Category"],["RISK_PROBABILITY","Risk Probability"],["RISK_IMPACT","Risk Impact"],["RISK_SEVERITY","Risk Severity"]] as const;
type Item={id:string;version:number;groupCode:string;code:string;name:string;displayOrder:number;active:boolean};const initial:FormState={};
function Fields({item}:{item?:Item}){return <div className="form-grid"><label className="field"><span>กลุ่ม</span><select className="control" name="groupCode" defaultValue={item?.groupCode??"SOLUTION_CATEGORY"}>{groups.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label className="field"><span>รหัส</span><input className="control" name="code" defaultValue={item?.code} required maxLength={100}/></label><label className="field"><span>ชื่อแสดงผล</span><input className="control" name="name" defaultValue={item?.name} required maxLength={255}/></label><label className="field"><span>ลำดับ</span><input className="control" name="displayOrder" type="number" min="0" max="100000" defaultValue={item?.displayOrder??0} required/></label><label className="field checkbox-field"><input name="active" type="checkbox" defaultChecked={item?.active??true}/> เปิดใช้งาน</label></div>;}
function Create(){const[state,action,pending]=useActionState(createSolutionReferenceAction,initial);return <form action={action} className="card form-card"><div className="card-header"><div><strong>เพิ่ม Reference Data</strong><small>ใช้ใน Solution Design, Components และ Traceability/Risk</small></div></div><div className="card-body"><Fields/><FormNotice state={state}/><button className="primary" disabled={pending}>{pending?"กำลังเพิ่ม…":"เพิ่มรายการ"}</button></div></form>;}
function Row({item}:{item:Item}){const[editing,setEditing]=useState(false);const[state,action,pending]=useActionState(updateSolutionReferenceAction.bind(null,item.id),initial);return <Fragment><tr><td>{item.groupCode}</td><td>{item.displayOrder}</td><td><strong>{item.code}</strong></td><td>{item.name}</td><td><span className={`badge ${item.active?"success":"muted"}`}>{item.active?"ใช้งาน":"ปิดใช้งาน"}</span></td><td><button type="button" className="secondary" onClick={()=>setEditing(value=>!value)}>{editing?"ปิด":"แก้ไข"}</button></td></tr>{editing&&<tr><td colSpan={6}><form action={action}><input type="hidden" name="expectedVersion" value={item.version}/><Fields item={item}/><FormNotice state={state}/><div className="actions"><button className="primary" disabled={pending}>{pending?"กำลังบันทึก…":"บันทึก"}</button><button type="button" className="secondary" onClick={()=>setEditing(false)}>ยกเลิก</button></div></form></td></tr>}</Fragment>;}
export function SolutionReferenceAdminConsole({items,pagination,filters}:{items:Item[];pagination:{page:number;total:number;totalPages:number;sort:string;order:"asc"|"desc"};filters:{q:string;groupCode:string}}){const params={...(filters.q?{q:filters.q}:{}),...(filters.groupCode?{groupCode:filters.groupCode}:{}),sort:pagination.sort,order:pagination.order};return <div className="service-category-admin"><Create/><section className="card"><div className="card-header"><div><strong>Solution Reference Data</strong><small>ค้นหา เรียงลำดับ และปิดใช้งานรายการได้จากจุดเดียว</small></div><span>{pagination.total} รายการ</span></div><form className="table-toolbar" action="/admin/solution-reference-data"><input className="control" type="search" name="q" defaultValue={filters.q} placeholder="ค้นหารหัสหรือชื่อ"/><select className="control" name="groupCode" defaultValue={filters.groupCode}><option value="">ทุกกลุ่ม</option>{groups.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><button className="secondary">ค้นหา</button>{(filters.q||filters.groupCode)&&<a className="secondary" href="/admin/solution-reference-data">ล้างค่า</a>}</form><div className="table-wrap"><table className="table"><thead><tr><SortableTableHeader basePath="/admin/solution-reference-data" column="groupCode" currentSort={pagination.sort} currentOrder={pagination.order} params={filters} label="กลุ่ม"/><SortableTableHeader basePath="/admin/solution-reference-data" column="displayOrder" currentSort={pagination.sort} currentOrder={pagination.order} params={filters} label="ลำดับ"/><SortableTableHeader basePath="/admin/solution-reference-data" column="code" currentSort={pagination.sort} currentOrder={pagination.order} params={filters} label="รหัส"/><SortableTableHeader basePath="/admin/solution-reference-data" column="name" currentSort={pagination.sort} currentOrder={pagination.order} params={filters} label="ชื่อ"/><SortableTableHeader basePath="/admin/solution-reference-data" column="active" currentSort={pagination.sort} currentOrder={pagination.order} params={filters} label="สถานะ"/><th>การทำงาน</th></tr></thead><tbody>{items.map(item=><Row key={`${item.id}-${item.version}`} item={item}/>)}</tbody></table>{!items.length&&<div className="empty">ไม่พบ Reference Data</div>}</div><PageNumberNavigation ariaLabel="แบ่งหน้า Solution Reference Data" basePath="/admin/solution-reference-data" itemCount={items.length} page={pagination.page} params={params} total={pagination.total} totalPages={pagination.totalPages} unit="รายการ"/></section></div>;}
