export type HelpAudience = "SALES" | "PRESALES" | "APPROVER" | "ADMIN" | "ALL";
export type HelpArticle = { slug: string; title: string; summary: string; audience: HelpAudience[]; category: string; tags: string[]; updatedAt: string; readingMinutes: number; sections: Array<{ title: string; body: string[] }>; faqs: Array<{ question: string; answer: string }>; relatedSlugs?: string[] };

export const helpAudienceLabels: Record<HelpAudience, string> = { ALL: "ทุกบทบาท", SALES: "ทีมขาย", PRESALES: "Presales / Coverage", APPROVER: "ผู้อนุมัติ", ADMIN: "ผู้ดูแลระบบ" };

export const helpArticles: HelpArticle[] = [
  { slug: "customer-to-opportunity", title: "เริ่มงานขายจาก Customer ไป Opportunity", summary: "วิธีสร้าง Customer, ตรวจข้อมูลซ้ำ, กำหนดเจ้าของ และเปิด Opportunity โดยไม่ข้ามสิทธิ์หรือ workflow", audience: ["SALES", "ADMIN"], category: "เริ่มต้นใช้งาน", tags: ["Customer", "Opportunity", "Ownership"], updatedAt: "2026-07-14", readingMinutes: 5, sections: [
    { title: "เริ่มจาก Customer", body: ["เปิดเมนูงานขาย > ลูกค้า แล้วค้นหาด้วยชื่อ เลขนิติบุคคล หรือ External ID ก่อนสร้างรายการใหม่ เพื่อลดข้อมูลซ้ำ", "เจ้าของและขอบเขตหน่วยงานถูกตรวจฝั่ง server การไม่เห็นปุ่มหรือรายการไม่ใช่ security control เพียงอย่างเดียว"] },
    { title: "สร้าง Opportunity", body: ["เลือก Customer และกรอก Flow มูลค่าประมาณการ โอกาสชนะ วันคาดว่าจะปิด และ Next Action", "Opportunity ใหม่เริ่มที่ QUALIFY เสมอ การเปลี่ยนขั้นตอนต้องใช้ Transition และกรอก evidence ตาม policy"] },
  ], faqs: [{ question: "แก้ Stage จากหน้าแก้ไข Opportunity ได้ไหม", answer: "ไม่ได้ ต้องใช้ Transition command เพื่อให้ระบบตรวจ policy, version และเขียน audit history" }], relatedSlugs: ["sales-pipeline-and-forecast", "quotation-and-approval"] },
  { slug: "sales-pipeline-and-forecast", title: "อ่าน Sales Pipeline และ Forecast", summary: "การใช้ period, weighted amount, forecast category, quality indicator และ immutable snapshot", audience: ["SALES", "APPROVER", "ADMIN"], category: "Pipeline", tags: ["Pipeline", "Forecast", "Snapshot"], updatedAt: "2026-07-14", readingMinutes: 4, sections: [
    { title: "Pipeline amount และ Weighted amount", body: ["Pipeline amount ใช้มูลค่าจาก Quote Version ที่มีหลักฐานก่อน แล้วจึง fallback ไป Opportunity", "Weighted amount คำนวณด้วย Decimal จากมูลค่าและ probability โดยใช้ authorization scope เดียวกับ Opportunity"] },
    { title: "คุณภาพข้อมูล", body: ["Quality panel ช่วยชี้รายการที่ไม่มี expected close date หรือ next action", "Snapshot เก็บ formula version, cutoff, scope และ item version เพื่อเปิดดูผลย้อนหลังได้โดยไม่เปลี่ยนตามข้อมูลปัจจุบัน"] },
  ], faqs: [{ question: "ปิด AI แล้วยังเห็น Deal Risk ไหม", answer: "เห็น deterministic risk signal ได้ตาม rule version; AI มีหน้าที่อธิบายเพิ่มเติมเท่านั้น" }], relatedSlugs: ["customer-to-opportunity"] },
  { slug: "quotation-and-approval", title: "สร้าง Quotation หลายรายการและส่ง Approval", summary: "วิธีกรอก Header, เพิ่มหลาย product, ตั้งราคา/ส่วนลด, ตรวจ floor price และส่งอนุมัติ", audience: ["SALES", "PRESALES", "APPROVER"], category: "Quotation", tags: ["Quote Version", "Floor Price", "Discount", "Approval"], updatedAt: "2026-07-14", readingMinutes: 6, sections: [
    { title: "Header และ Detail lines", body: ["Header ผูก Opportunity, validity, currency และหมายเหตุ ส่วน Customer จะสืบทอดจาก Opportunity", "Detail รองรับหลาย product แต่ละบรรทัดมีจำนวน ราคาขาย Floor Price ส่วนลด และยอดสุทธิ"] },
    { title: "Floor Price และ Version", body: ["ระบบคำนวณด้วย Decimal ฝั่ง server และไม่ยอมให้ราคาสุทธิต่อหน่วยต่ำกว่า Floor Price ที่ยืนยันใน Product Catalog", "เมื่อ Quote ถูก submit หรือ approved แล้ว การแก้ไขต้องสร้าง version ใหม่ และ approval เดิมจะถูก supersede ตาม policy"] },
    { title: "ก่อนส่งอนุมัติ", body: ["ตรวจ Coverage, Solution และ confirmed cost gates ตาม approval policy ระบบไม่มี auto-approve path", "ผู้อนุมัติต้องมี role/authority ที่ effective และต้องไม่ใช่ maker เมื่อ policy บังคับ maker-checker"] },
  ], faqs: [{ question: "ทำไมบางสินค้าแสดงว่ายังไม่กำหนด Floor Price", answer: "Product นั้นยังไม่มี floor price ที่ได้รับการยืนยัน ผู้ดูแลต้องบันทึกข้อมูลราคาจริงก่อนใช้เป็น commercial gate" }, { question: "ส่วนลดคิดอย่างไร", answer: "ส่วนลดคิดแยกต่อบรรทัดจากราคาขาย × จำนวน และยอดรวมถูกทำซ้ำได้จาก immutable Quote Version Item" }], relatedSlugs: ["workflow-administration"] },
  { slug: "workflow-administration", title: "จัดการ Workflow Policy และ Authority", summary: "แนวทางสร้าง policy version, effective dates, role assignment, authority grant และ confirmed cost", audience: ["ADMIN"], category: "Administration", tags: ["Policy", "Authority", "Role", "Audit"], updatedAt: "2026-07-14", readingMinutes: 5, sections: [
    { title: "สร้าง version แทนแก้ทับ", body: ["Transition และ Approval Policy ทุกการเปลี่ยนแปลงต้องสร้าง version ใหม่ กำหนด effectiveFrom/effectiveTo และเก็บ definition snapshot", "ห้าม hard-code approval level, role หรือ threshold ใน UI/application behavior"] },
    { title: "Authority และ Separation of Duties", body: ["Authority grant ต้องตรง permission, role, scope, segment, maximum amount และ effective period", "ควรมีผู้ใช้อย่างน้อยสองคนเพื่อทดสอบ maker-checker ด้วยตัวตนจริง"] },
  ], faqs: [{ question: "ซ่อนปุ่มเพียงพอสำหรับจำกัดสิทธิ์ไหม", answer: "ไม่เพียงพอ ทุก mutation ตรวจ authorization ฝั่ง server และ privileged action ต้องเขียน audit" }], relatedSlugs: ["quotation-and-approval"] },
  { slug: "notifications-and-tasks", title: "ใช้ Notification และ Activity ให้ไม่พลาดงาน", summary: "รายการแจ้งเตือนบน Header มาจากกิจกรรมที่รับผิดชอบและสถานะใบเสนอราคาของผู้ใช้", audience: ["ALL"], category: "การทำงานประจำวัน", tags: ["Notification", "Activity", "SLA"], updatedAt: "2026-07-14", readingMinutes: 3, sections: [
    { title: "Notification panel", body: ["กดไอคอนกระดิ่งบน Header เพื่อดูงานใกล้ครบกำหนด งานเลยกำหนด และ Quote ที่กำลังรอหรือถูกส่งกลับ", "รายการถูก query ตามผู้ใช้ปัจจุบันและลิงก์กลับไปยัง business record ที่เกี่ยวข้อง"] },
  ], faqs: [{ question: "ทำไมไม่เห็น notification ของคนอื่น", answer: "ระบบจำกัดตาม owner/maker เพื่อป้องกันข้อมูลข้าม scope" }] },
];

export function getHelpArticle(slug: string) { return helpArticles.find((article) => article.slug === slug); }
export function getRelatedHelpArticles(article: HelpArticle) { return (article.relatedSlugs ?? []).flatMap((slug) => { const item = getHelpArticle(slug); return item ? [item] : []; }); }
export function searchHelpArticles(query: string, audience: string) { const normalized = query.trim().toLocaleLowerCase("th-TH"); return helpArticles.filter((article) => (!audience || article.audience.includes(audience as HelpAudience) || article.audience.includes("ALL")) && (!normalized || [article.title, article.summary, article.category, ...article.tags].join(" ").toLocaleLowerCase("th-TH").includes(normalized))); }
