import { NextResponse } from "next/server";
import { ZodError } from "zod";
import { getSession } from "@/lib/auth";
import { loadAuthorizationContext } from "@/lib/authorization/authorization-context";
import { loadProspectPermissions, ProspectAccessError } from "@/lib/prospect/prospect-authorization";
import { ProspectConversionError, ProspectDuplicateResolutionRequiredError, ProspectValidationError, ProspectVersionConflictError } from "@/lib/prospect/prospect-service";
import { ProspectDocumentValidationError } from "@/lib/prospect/prospect-document-service";
import { DocumentStorageConfigurationError, DocumentStorageOperationError, UnsafeDocumentError } from "@/lib/prospect/prospect-document-storage";
import { DataRetentionAccessError, DataRetentionValidationError, DataRetentionVersionConflictError, PermanentDeleteBlockedError } from "@/lib/data-retention/data-retention-service";
import { workflowCorrelationId, workflowUnauthenticated } from "../workflow-api-response";

export { workflowCorrelationId };
export async function prospectActor(request: Request) { const correlationId = workflowCorrelationId(request), session = await getSession(); if (!session) return { response: workflowUnauthenticated(correlationId), correlationId } as const; const authorization = await loadAuthorizationContext({ actorId: session.id, legacyRole: session.role }); const permissions = await loadProspectPermissions(authorization); return { actor: { id: session.id, authorization, permissions }, session, correlationId } as const; }
export function prospectApiError(error: unknown, correlationId: string) { let status = 500, code = "INTERNAL_ERROR", message = "ไม่สามารถดำเนินการได้"; let data: unknown; if (error instanceof ProspectValidationError || error instanceof ProspectDocumentValidationError || error instanceof DataRetentionValidationError || error instanceof ZodError || error instanceof SyntaxError) { status = 400; code = "VALIDATION_FAILED"; data = error instanceof ProspectValidationError || error instanceof ProspectDocumentValidationError || error instanceof DataRetentionValidationError ? error.issues : error instanceof ZodError ? error.flatten().fieldErrors : undefined; } else if (error instanceof ProspectAccessError || error instanceof DataRetentionAccessError) { status = 404; code = "RESOURCE_NOT_FOUND"; } else if (error instanceof ProspectVersionConflictError || error instanceof DataRetentionVersionConflictError) { status = 409; code = "VERSION_CONFLICT"; } else if (error instanceof PermanentDeleteBlockedError) { status = 422; code = "PERMANENT_DELETE_BLOCKED"; message = error.message; data = { references: error.references }; } else if (error instanceof ProspectDuplicateResolutionRequiredError) { status = 409; code = "DUPLICATE_RESOLUTION_REQUIRED"; data = error.candidates; } else if (error instanceof ProspectConversionError) { status = 422; code = "CONVERSION_DENIED"; message = error.message; } else if (error instanceof UnsafeDocumentError) { status = 422; code = "DOCUMENT_UNSAFE"; message = error.message; } else if (error instanceof DocumentStorageConfigurationError || error instanceof DocumentStorageOperationError) { status = 503; code = "DOCUMENT_SERVICE_UNAVAILABLE"; message = error.message; } return NextResponse.json({ error: { code, message, ...(data ? { data } : {}), retryable: status === 503, correlationId } }, { status }); }
export function prospectIdempotencyKey(request: Request, correlationId: string) { const key = request.headers.get("idempotency-key")?.trim(); return key && key.length <= 191 ? key : NextResponse.json({ error: { code: "IDEMPOTENCY_KEY_REQUIRED", message: "Idempotency-Key is required", retryable: false, correlationId } }, { status: 400 }); }
