import { ProspectHeatLevel, ProspectSource, ProspectStatus, type Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { PERMISSIONS } from "@/lib/authorization/permission-policy";
import { buildProspectScopeWhere, requireProspectPermission } from "@/lib/prospect/prospect-authorization";
import { createProspectRuntime } from "@/lib/prospect/prospect-runtime";
import { prisma } from "@/lib/prisma";
import { prospectActor, prospectApiError, prospectIdempotencyKey } from "./prospect-api";

export async function GET(request: Request) { const auth = await prospectActor(request); if ("response" in auth) return auth.response; try { requireProspectPermission(auth.actor.permissions, PERMISSIONS.prospectView); const url = new URL(request.url), limit = Math.min(100, Math.max(1, Number(url.searchParams.get("limit") ?? 50))), page = Math.max(1, Number(url.searchParams.get("page") ?? 1)); const status = url.searchParams.get("status"), heat = url.searchParams.get("heatLevel"), source = url.searchParams.get("source"), q = url.searchParams.get("q")?.trim(), province = url.searchParams.get("province"), ownerId = url.searchParams.get("ownerId"), overdue = url.searchParams.get("overdue") === "1"; const where: Prisma.ProspectWhereInput = { AND: [buildProspectScopeWhere(auth.actor.authorization, auth.actor.permissions), status && Object.values(ProspectStatus).includes(status as ProspectStatus) ? { status: status as ProspectStatus } : {}, heat && Object.values(ProspectHeatLevel).includes(heat as ProspectHeatLevel) ? { heatLevel: heat as ProspectHeatLevel } : {}, source && Object.values(ProspectSource).includes(source as ProspectSource) ? { source: source as ProspectSource } : {}, province ? { province } : {}, ownerId ? { ownerId } : {}, overdue ? { nextFollowUpAt: { lt: new Date() }, status: { notIn: ["CONVERTED", "LOST", "ARCHIVED"] } } : {}, q ? { OR: [{ prospectCode: { contains: q } }, { companyName: { contains: q } }, { companyNameEnglish: { contains: q } }, { taxId: { contains: q } }, { contacts: { some: { OR: [{ email: { contains: q } }, { phone: { contains: q } }, { mobile: { contains: q } }], deletedAt: null } } }] } : {}] }; const [data, total] = await Promise.all([prisma.prospect.findMany({ where, include: { owner: { select: { id: true, name: true } }, industry: { select: { id: true, name: true } }, contacts: { where: { isPrimary: true, deletedAt: null }, take: 1 } }, orderBy: [{ updatedAt: "desc" }, { id: "desc" }], skip: (page - 1) * limit, take: limit }), prisma.prospect.count({ where })]); return NextResponse.json({ data, page: { page, limit, total, hasMore: page * limit < total }, meta: { correlationId: auth.correlationId } }); } catch (error) { return prospectApiError(error, auth.correlationId); } }
export async function POST(request: Request) { const auth = await prospectActor(request); if ("response" in auth) return auth.response; const key = prospectIdempotencyKey(request, auth.correlationId); if (key instanceof NextResponse) return key; try { const result = await createProspectRuntime().create(auth.actor, await request.json(), auth.correlationId, key); return NextResponse.json({ data: result, meta: { correlationId: auth.correlationId } }, { status: 201 }); } catch (error) { return prospectApiError(error, auth.correlationId); } }
