import { LeadSource,LeadStatus } from "@prisma/client";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { loadAuthorizationContext } from "@/lib/authorization/authorization-context";
import { parseLeadCsv } from "@/lib/lead/csv";
import { buildLeadScopeWhere } from "@/lib/lead/prisma-lead-repository";
import { LEAD_IMPORT_ROLES } from "@/lib/lead/lead-rules";
import { prisma } from "@/lib/prisma";
import { workflowApiError,workflowCorrelationId,workflowUnauthenticated } from "../../../workflow-api-response";
export async function POST(request:Request){const correlationId=workflowCorrelationId(request),session=await getSession();if(!session)return workflowUnauthenticated(correlationId);try{const authorization=await loadAuthorizationContext({actorId:session.id,legacyRole:session.role});if(!authorization.assignments.some(item=>(LEAD_IMPORT_ROLES as readonly string[]).includes(item.role)))return NextResponse.json({error:{code:"FORBIDDEN",message:"ไม่มีสิทธิ์นำเข้า Lead",retryable:false,correlationId}},{status:403});const body=await request.text();if(body.length>2_000_000)return NextResponse.json({error:{code:"IMPORT_FILE_TOO_LARGE",message:"ไฟล์ต้องไม่เกิน 2 MB",retryable:false,correlationId}},{status:413});const records=parseLeadCsv(body);if(records.length>1000)return NextResponse.json({error:{code:"IMPORT_LIMIT_EXCEEDED",message:"นำเข้าได้ไม่เกิน 1,000 แถว",retryable:false,correlationId}},{status:413});const companies=[...new Set(records.map(row=>row.company).filter(Boolean))],emails=[...new Set(records.map(row=>row.contactEmail).filter(Boolean))],phones=[...new Set(records.map(row=>row.contactPhone).filter(Boolean))];const duplicates=await prisma.lead.findMany({where:{AND:[buildLeadScopeWhere(authorization),{status:{not:LeadStatus.ARCHIVED}},{OR:[...(companies.length?[{company:{in:companies}}]:[]),...(emails.length?[{contactEmail:{in:emails}}]:[]),...(phones.length?[{contactPhone:{in:phones}}]:[])]}]},select:{id:true,company:true,contactEmail:true,contactPhone:true},take:2000});const rows=records.map((row,index)=>{const errors:string[]=[];if(!Object.values(LeadSource).includes(row.source as LeadSource))errors.push("source ไม่ถูกต้อง");if(!row.contactEmail&&!row.contactPhone)errors.push("ต้องมี email หรือ phone");if(!row.recommendedProducts&&!row.requirementSummary)errors.push("ต้องมี product หรือ requirement");const matches=duplicates.filter(item=>item.company===row.company||Boolean(row.contactEmail&&item.contactEmail===row.contactEmail)||Boolean(row.contactPhone&&item.contactPhone===row.contactPhone));return{row:index+2,valid:errors.length===0,errors,duplicateCandidates:matches.map(item=>({id:item.id,reasons:[item.company===row.company?"COMPANY":null,row.contactEmail&&item.contactEmail===row.contactEmail?"EMAIL":null,row.contactPhone&&item.contactPhone===row.contactPhone?"PHONE":null].filter(Boolean) }))};});return NextResponse.json({data:{total:rows.length,valid:rows.filter(row=>row.valid).length,invalid:rows.filter(row=>!row.valid).length,duplicates:rows.filter(row=>row.duplicateCandidates.length).length,rows},meta:{correlationId}});}catch(error){return workflowApiError(error,correlationId);}}
