import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { assertPermission,PERMISSIONS } from "@/lib/authorization/permission-policy";
import { contractEditSchema } from "@/lib/contract/contracts";
import { createContractRuntime } from "@/lib/contract/contract-runtime";
import { prisma } from "@/lib/prisma";
import { requireIdempotencyKey,workflowApiError,workflowCorrelationId,workflowUnauthenticated } from "../../workflow-api-response";
import { contractActor } from "../contract-api";
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const correlationId=workflowCorrelationId(request),session=await getSession();if(!session)return workflowUnauthenticated(correlationId);try{assertPermission(session,PERMISSIONS.contractView);const actor=await contractActor(session),id=(await params).id,runtime=createContractRuntime(),summary=await runtime.repository.transaction(tx=>runtime.repository.find(id,actor.authorization,tx));if(!summary)return NextResponse.json({error:{code:"RESOURCE_NOT_FOUND",message:"ไม่พบสัญญา",retryable:false,correlationId}},{status:404});const data=await prisma.contract.findUnique({where:{id:summary.id},include:{status:true,contractType:true,versions:{orderBy:{versionNumber:"desc"},include:{items:{orderBy:{sortOrder:"asc"}}}},reviews:{orderBy:{createdAt:"desc"}},documents:{include:{versions:{orderBy:{versionNumber:"desc"}}}},signatures:{orderBy:{signedAt:"desc"}},amendments:{orderBy:{createdAt:"desc"}},renewals:{include:{reminders:true},orderBy:{renewalDate:"desc"}},purchaseOrders:{orderBy:{poDate:"desc"}},serviceOrders:{orderBy:{createdAt:"desc"}}}});return NextResponse.json({data,meta:{correlationId}});}catch(error){return workflowApiError(error,correlationId);}}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){const correlationId=workflowCorrelationId(request),session=await getSession();if(!session)return workflowUnauthenticated(correlationId);const key=requireIdempotencyKey(request,correlationId);if(typeof key!=="string")return key;try{const data=await createContractRuntime().service.edit(await contractActor(session),(await params).id,contractEditSchema.parse(await request.json()),correlationId);return NextResponse.json({data,meta:{correlationId}});}catch(error){return workflowApiError(error,correlationId);}}
