ALTER TABLE `Activity`
  MODIFY `type` ENUM('CALL','PHONE_CALL','EMAIL','LINE','MEETING','SITE_VISIT','CUSTOMER_VISIT','ONLINE_MEETING','VIDEO_CONFERENCE','DEMO','PRESENTATION','NOTE','FOLLOW_UP','TASK','DOCUMENT_REQUEST','OTHER') NOT NULL,
  ADD COLUMN `prospectId` VARCHAR(191) NULL,
  ADD COLUMN `description` TEXT NULL, ADD COLUMN `activityAt` DATETIME(3) NULL,
  ADD COLUMN `startsAt` DATETIME(3) NULL, ADD COLUMN `endsAt` DATETIME(3) NULL,
  ADD COLUMN `participants` LONGTEXT NULL, ADD COLUMN `outcome` TEXT NULL,
  ADD COLUMN `customerFeedback` TEXT NULL, ADD COLUMN `nextAction` TEXT NULL,
  ADD COLUMN `nextFollowUpAt` DATETIME(3) NULL;

CREATE TABLE `Industry` (`id` VARCHAR(191) NOT NULL,`code` VARCHAR(100) NOT NULL,`name` VARCHAR(255) NOT NULL,`active` BOOLEAN NOT NULL DEFAULT true,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`updatedAt` DATETIME(3) NOT NULL,PRIMARY KEY(`id`),UNIQUE INDEX `Industry_code_key`(`code`)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `SalesTerritory` (`id` VARCHAR(191) NOT NULL,`code` VARCHAR(100) NOT NULL,`name` VARCHAR(255) NOT NULL,`region` VARCHAR(100) NULL,`active` BOOLEAN NOT NULL DEFAULT true,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`updatedAt` DATETIME(3) NOT NULL,PRIMARY KEY(`id`),UNIQUE INDEX `SalesTerritory_code_key`(`code`)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectNumberSequence` (`id` VARCHAR(32) NOT NULL,`nextValue` INTEGER NOT NULL DEFAULT 0,`updatedAt` DATETIME(3) NOT NULL,PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectScoringRuleVersion` (`id` VARCHAR(191) NOT NULL,`version` INTEGER NOT NULL,`active` BOOLEAN NOT NULL DEFAULT false,`weights` LONGTEXT NOT NULL,`hotThreshold` INTEGER NOT NULL DEFAULT 75,`warmThreshold` INTEGER NOT NULL DEFAULT 40,`createdById` VARCHAR(191) NOT NULL,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE INDEX `ProspectScoringRuleVersion_version_key`(`version`),INDEX `ProspectScoringRuleVersion_active_version_idx`(`active`,`version`)) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE `Prospect` (
`id` VARCHAR(191) NOT NULL,`prospectCode` VARCHAR(32) NOT NULL,`companyName` VARCHAR(255) NOT NULL,`companyNameEnglish` VARCHAR(255) NULL,`normalizedCompanyName` VARCHAR(255) NOT NULL,`normalizedCompanyEnglish` VARCHAR(255) NULL,`taxId` VARCHAR(32) NULL,`branchNumber` VARCHAR(20) NULL,
`customerType` VARCHAR(100) NULL,`organizationType` VARCHAR(100) NULL,`industryId` VARCHAR(191) NULL,`subIndustry` VARCHAR(191) NULL,`companySize` VARCHAR(100) NULL,`numberOfEmployees` INTEGER NULL,`estimatedAnnualRevenue` DECIMAL(19,4) NULL,`website` VARCHAR(500) NULL,`websiteDomain` VARCHAR(255) NULL,`companyDescription` TEXT NULL,
`address` TEXT NULL,`subDistrict` VARCHAR(191) NULL,`district` VARCHAR(191) NULL,`province` VARCHAR(191) NULL,`postalCode` VARCHAR(20) NULL,`region` VARCHAR(100) NULL,`latitude` DECIMAL(10,7) NULL,`longitude` DECIMAL(10,7) NULL,`salesTerritoryId` VARCHAR(191) NULL,`responsibleBusinessUnitId` VARCHAR(191) NULL,
`currentTelecomProvider` TEXT NULL,`currentInternetProvider` TEXT NULL,`currentCloudProvider` TEXT NULL,`currentSecurityProvider` TEXT NULL,`existingSolutions` TEXT NULL,`currentContractEndDate` DATETIME(3) NULL,`numberOfBranches` INTEGER NULL,`businessPainPoints` TEXT NULL,`expectedBudget` DECIMAL(19,4) NULL,`expectedPurchasePeriod` VARCHAR(191) NULL,`estimatedOpportunityValue` DECIMAL(19,4) NULL,`currency` CHAR(3) NOT NULL DEFAULT 'THB',`procurementMethod` VARCHAR(191) NULL,`projectType` VARCHAR(191) NULL,
`source` ENUM('MANUAL','WEBSITE','LINE_OA','CALL_CENTER','WALK_IN','EVENT','PARTNER','REFERRAL','EXISTING_CUSTOMER','TENDER','GOVERNMENT_PROJECT','WEB_SCRAPER','COMPANY_REGISTRY','IMPORT','OTHER') NOT NULL,`sourceName` VARCHAR(255) NULL,`campaignId` VARCHAR(191) NULL,`referralName` VARCHAR(255) NULL,`partnerId` VARCHAR(191) NULL,`importedFileName` VARCHAR(255) NULL,`sourceReference` VARCHAR(500) NULL,
`ownerId` VARCHAR(191) NOT NULL,`backupOwnerId` VARCHAR(191) NULL,`salesTeamId` VARCHAR(191) NULL,`salesManagerId` VARCHAR(191) NULL,`assignedAt` DATETIME(3) NULL,`assignedById` VARCHAR(191) NULL,`lastContactAt` DATETIME(3) NULL,`nextFollowUpAt` DATETIME(3) NULL,`lastActivityType` ENUM('CALL','PHONE_CALL','EMAIL','LINE','MEETING','SITE_VISIT','CUSTOMER_VISIT','ONLINE_MEETING','VIDEO_CONFERENCE','DEMO','PRESENTATION','NOTE','FOLLOW_UP','TASK','DOCUMENT_REQUEST','OTHER') NULL,`followUpStatus` VARCHAR(100) NULL,`contactAttemptCount` INTEGER NOT NULL DEFAULT 0,
`status` ENUM('NEW','ASSIGNED','CONTACTED','INTERESTED','QUALIFYING','QUALIFIED','NOT_INTERESTED','UNREACHABLE','LOST','CONVERTED','ARCHIVED') NOT NULL DEFAULT 'NEW',`aiSummary` TEXT NULL,`aiOpportunityScore` INTEGER NULL,`aiConfidenceScore` INTEGER NULL,`aiRiskScore` INTEGER NULL,`calculatedScore` INTEGER NOT NULL DEFAULT 0,`heatLevel` ENUM('HOT','WARM','COLD') NOT NULL DEFAULT 'COLD',`recommendedProducts` TEXT NULL,`suggestedQuestions` LONGTEXT NULL,`suggestedNextAction` TEXT NULL,`enrichmentData` LONGTEXT NULL,`enrichmentStatus` ENUM('NOT_REQUESTED','QUEUED','PROCESSING','READY','CONFIRMED','REJECTED','FAILED') NOT NULL DEFAULT 'NOT_REQUESTED',`enrichmentUpdatedAt` DATETIME(3) NULL,
`convertedLeadId` VARCHAR(191) NULL,`convertedAt` DATETIME(3) NULL,`convertedById` VARCHAR(191) NULL,`conversionNote` TEXT NULL,`notes` TEXT NULL,`version` INTEGER NOT NULL DEFAULT 1,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`createdById` VARCHAR(191) NOT NULL,`updatedAt` DATETIME(3) NOT NULL,`updatedById` VARCHAR(191) NOT NULL,`deletedAt` DATETIME(3) NULL,`deletedById` VARCHAR(191) NULL,`mergedIntoProspectId` VARCHAR(191) NULL,
PRIMARY KEY(`id`),UNIQUE INDEX `Prospect_prospectCode_key`(`prospectCode`),UNIQUE INDEX `Prospect_convertedLeadId_key`(`convertedLeadId`),INDEX `Prospect_ownerId_status_updatedAt_idx`(`ownerId`,`status`,`updatedAt`),INDEX `Prospect_unit_status_updatedAt_idx`(`responsibleBusinessUnitId`,`status`,`updatedAt`),INDEX `Prospect_team_status_updatedAt_idx`(`salesTeamId`,`status`,`updatedAt`),INDEX `Prospect_status_heat_updatedAt_idx`(`status`,`heatLevel`,`updatedAt`),INDEX `Prospect_taxId_idx`(`taxId`),INDEX `Prospect_normalizedCompanyName_idx`(`normalizedCompanyName`),INDEX `Prospect_websiteDomain_idx`(`websiteDomain`),INDEX `Prospect_nextFollowUpAt_status_idx`(`nextFollowUpAt`,`status`),INDEX `Prospect_deletedAt_updatedAt_idx`(`deletedAt`,`updatedAt`),
CONSTRAINT `Prospect_industry_fkey` FOREIGN KEY(`industryId`) REFERENCES `Industry`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_territory_fkey` FOREIGN KEY(`salesTerritoryId`) REFERENCES `SalesTerritory`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_unit_fkey` FOREIGN KEY(`responsibleBusinessUnitId`) REFERENCES `OrganizationUnit`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_campaign_fkey` FOREIGN KEY(`campaignId`) REFERENCES `Campaign`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_owner_fkey` FOREIGN KEY(`ownerId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `Prospect_backup_fkey` FOREIGN KEY(`backupOwnerId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_team_fkey` FOREIGN KEY(`salesTeamId`) REFERENCES `OrganizationUnit`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_manager_fkey` FOREIGN KEY(`salesManagerId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_lead_fkey` FOREIGN KEY(`convertedLeadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `Prospect_merge_fkey` FOREIGN KEY(`mergedIntoProspectId`) REFERENCES `Prospect`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

ALTER TABLE `Activity` ADD INDEX `Activity_prospectId_createdAt_idx`(`prospectId`,`createdAt`),ADD CONSTRAINT `Activity_prospect_fkey` FOREIGN KEY(`prospectId`) REFERENCES `Prospect`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE `ProspectContact` (`id` VARCHAR(191) NOT NULL,`prospectId` VARCHAR(191) NOT NULL,`leadId` VARCHAR(191) NULL,`name` VARCHAR(255) NOT NULL,`position` VARCHAR(191) NULL,`department` VARCHAR(191) NULL,`phone` VARCHAR(100) NULL,`mobile` VARCHAR(100) NULL,`email` VARCHAR(320) NULL,`lineId` VARCHAR(191) NULL,`preferredContactChannel` ENUM('PHONE','MOBILE','EMAIL','LINE','MEETING','OTHER') NULL,`isPrimary` BOOLEAN NOT NULL DEFAULT false,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`createdById` VARCHAR(191) NOT NULL,`updatedAt` DATETIME(3) NOT NULL,`updatedById` VARCHAR(191) NOT NULL,`deletedAt` DATETIME(3) NULL,`deletedById` VARCHAR(191) NULL,PRIMARY KEY(`id`),INDEX `PC_prospect_primary_idx`(`prospectId`,`deletedAt`,`isPrimary`),INDEX `PC_lead_idx`(`leadId`,`deletedAt`),INDEX `PC_email_idx`(`email`),INDEX `PC_phone_idx`(`phone`),INDEX `PC_mobile_idx`(`mobile`),CONSTRAINT `PC_prospect_fkey` FOREIGN KEY(`prospectId`) REFERENCES `Prospect`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `PC_lead_fkey` FOREIGN KEY(`leadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectStatusHistory` (`id` VARCHAR(191) NOT NULL,`prospectId` VARCHAR(191) NOT NULL,`fromStatus` ENUM('NEW','ASSIGNED','CONTACTED','INTERESTED','QUALIFYING','QUALIFIED','NOT_INTERESTED','UNREACHABLE','LOST','CONVERTED','ARCHIVED') NOT NULL,`toStatus` ENUM('NEW','ASSIGNED','CONTACTED','INTERESTED','QUALIFYING','QUALIFIED','NOT_INTERESTED','UNREACHABLE','LOST','CONVERTED','ARCHIVED') NOT NULL,`reason` VARCHAR(1000) NULL,`actorId` VARCHAR(191) NOT NULL,`correlationId` VARCHAR(191) NOT NULL,`transitionedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),INDEX `PSH_prospect_time_idx`(`prospectId`,`transitionedAt`),CONSTRAINT `PSH_prospect_fkey` FOREIGN KEY(`prospectId`) REFERENCES `Prospect`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectAssignmentHistory` (`id` VARCHAR(191) NOT NULL,`prospectId` VARCHAR(191) NOT NULL,`fromOwnerId` VARCHAR(191) NULL,`toOwnerId` VARCHAR(191) NOT NULL,`actorId` VARCHAR(191) NOT NULL,`reason` VARCHAR(1000) NULL,`assignedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),INDEX `PAH_prospect_time_idx`(`prospectId`,`assignedAt`),CONSTRAINT `PAH_prospect_fkey` FOREIGN KEY(`prospectId`) REFERENCES `Prospect`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectCommandReceipt` (`id` VARCHAR(191) NOT NULL,`actorId` VARCHAR(191) NOT NULL,`idempotencyKey` VARCHAR(191) NOT NULL,`command` VARCHAR(100) NOT NULL,`prospectId` VARCHAR(191) NOT NULL,`resultVersion` INTEGER NOT NULL,`resultLeadId` VARCHAR(191) NULL,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE INDEX `PCR_actor_key_command_key`(`actorId`,`idempotencyKey`,`command`),INDEX `PCR_prospect_time_idx`(`prospectId`,`createdAt`),CONSTRAINT `PCR_prospect_fkey` FOREIGN KEY(`prospectId`) REFERENCES `Prospect`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectSavedView` (`id` VARCHAR(191) NOT NULL,`userId` VARCHAR(191) NOT NULL,`name` VARCHAR(100) NOT NULL,`query` LONGTEXT NOT NULL,`columns` LONGTEXT NULL,`isDefault` BOOLEAN NOT NULL DEFAULT false,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`updatedAt` DATETIME(3) NOT NULL,PRIMARY KEY(`id`),UNIQUE INDEX `PSV_user_name_key`(`userId`,`name`),INDEX `PSV_user_default_idx`(`userId`,`isDefault`)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectMergeHistory` (`id` VARCHAR(191) NOT NULL,`sourceProspectId` VARCHAR(191) NOT NULL,`targetProspectId` VARCHAR(191) NOT NULL,`actorId` VARCHAR(191) NOT NULL,`reason` VARCHAR(1000) NOT NULL,`correlationId` VARCHAR(191) NOT NULL,`mergedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),INDEX `PMH_source_idx`(`sourceProspectId`,`mergedAt`),INDEX `PMH_target_idx`(`targetProspectId`,`mergedAt`)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectImportBatch` (`id` VARCHAR(191) NOT NULL,`actorId` VARCHAR(191) NOT NULL,`idempotencyKey` VARCHAR(191) NOT NULL,`fileName` VARCHAR(255) NOT NULL,`fileHash` CHAR(64) NOT NULL,`status` ENUM('PREVIEWED','PROCESSING','COMPLETED','PARTIAL','FAILED') NOT NULL,`totalRows` INTEGER NOT NULL,`importedRows` INTEGER NOT NULL DEFAULT 0,`failedRows` INTEGER NOT NULL DEFAULT 0,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`completedAt` DATETIME(3) NULL,PRIMARY KEY(`id`),UNIQUE INDEX `PIB_key`(`idempotencyKey`),INDEX `PIB_actor_time_idx`(`actorId`,`createdAt`)) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `ProspectImportRow` (`id` VARCHAR(191) NOT NULL,`batchId` VARCHAR(191) NOT NULL,`rowNumber` INTEGER NOT NULL,`status` ENUM('VALID','WARNING','DUPLICATE','ERROR','IMPORTED') NOT NULL,`normalized` LONGTEXT NOT NULL,`errors` LONGTEXT NULL,`prospectId` VARCHAR(191) NULL,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE INDEX `PIR_batch_row_key`(`batchId`,`rowNumber`),CONSTRAINT `PIR_batch_fkey` FOREIGN KEY(`batchId`) REFERENCES `ProspectImportBatch`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `PIR_prospect_fkey` FOREIGN KEY(`prospectId`) REFERENCES `Prospect`(`id`) ON DELETE SET NULL ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4;
CREATE TABLE `SalesDocument` (`id` VARCHAR(191) NOT NULL,`prospectId` VARCHAR(191) NULL,`leadId` VARCHAR(191) NULL,`objectKey` VARCHAR(500) NOT NULL,`objectKeyHash` CHAR(64) NOT NULL,`contentHash` CHAR(64) NOT NULL,`fileName` VARCHAR(255) NOT NULL,`mimeType` VARCHAR(191) NOT NULL,`sizeBytes` INTEGER NOT NULL,`category` VARCHAR(100) NOT NULL,`uploadedById` VARCHAR(191) NOT NULL,`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`deletedAt` DATETIME(3) NULL,`deletedById` VARCHAR(191) NULL,PRIMARY KEY(`id`),UNIQUE INDEX `SalesDocument_objectKeyHash_key`(`objectKeyHash`),INDEX `SD_prospect_idx`(`prospectId`,`deletedAt`,`createdAt`),INDEX `SD_lead_idx`(`leadId`,`deletedAt`,`createdAt`),INDEX `SD_hash_idx`(`contentHash`),CONSTRAINT `SD_prospect_fkey` FOREIGN KEY(`prospectId`) REFERENCES `Prospect`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT `SD_lead_fkey` FOREIGN KEY(`leadId`) REFERENCES `Lead`(`id`) ON DELETE SET NULL ON UPDATE CASCADE) DEFAULT CHARACTER SET utf8mb4;
