export const NAVIGATION_PERMISSIONS = {
  prospects: "navigation.prospects.view",
  leads: "navigation.leads.view",
  customers: "navigation.customers.view",
  opportunities: "navigation.opportunities.view",
  activities: "navigation.activities.view",
  pipeline: "navigation.pipeline.view",
  coverage: "navigation.coverage.view",
  solutionDesigns: "navigation.solution-designs.view",
  siteSurveys: "navigation.site-surveys.view",
  boqs: "navigation.boqs.view",
  products: "navigation.products.view",
  proposals: "navigation.proposals.view",
  quotes: "navigation.quotes.view",
  contracts: "navigation.contracts.view",
  approvals: "navigation.approvals.view",
  adminUsers: "navigation.admin.users.view",
  adminOrganization: "navigation.admin.organization.view",
  adminAudit: "navigation.admin.audit.view",
  adminDeletedRecords: "navigation.admin.deleted-records.view",
  adminAiSettings: "navigation.admin.ai-settings.view",
  adminRiskRules: "navigation.admin.risk-rules.view",
  adminWorkflow: "navigation.admin.workflow.view",
  adminLeadManagement: "navigation.admin.lead-management.view",
  adminServiceCategories: "navigation.admin.service-categories.view",
} as const;

export const QUICK_CREATE_PERMISSIONS = {
  prospect: "prospect.create",
  lead: "lead.create",
  customer: "customer.create",
  opportunity: "opportunity.create",
  activity: "activity.create",
  proposal: "proposal.manage",
  quote: "quote.manage",
  contract: "contract.manage",
} as const;
