import { LeadStatus, LeadTemperature, Prisma } from "@prisma/client";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { loadAuthorizationContext } from "@/lib/authorization/authorization-context";
import { createLeadRuntime } from "@/lib/lead/lead-runtime";
import { buildLeadScopeWhere } from "@/lib/lead/prisma-lead-repository";
import { prisma } from "@/lib/prisma";
import { requireIdempotencyKey, workflowApiError, workflowCorrelationId, workflowUnauthenticated } from "../workflow-api-response";

function createPayload(body: Record<string,unknown>) { return { company: body.company, contactName: body.contactName, contactEmail: body.contactEmail ?? "", contactPhone: body.contactPhone, source: body.source, status: body.status ?? "NEW", score: body.score ?? 0, recommendedProducts: body.recommendedProducts, notes: body.notes, customerId: body.customerId, duplicateOverrideReason: body.duplicateOverrideReason }; }
export async function GET(request:Request){const correlationId=workflowCorrelationId(request);const session=await getSession();if(!session)return workflowUnauthenticated(correlationId);try{const url=new URL(request.url);const authorization=await loadAuthorizationContext({actorId:session.id,legacyRole:session.role});const limit=Math.min(100,Math.max(1,Number(url.searchParams.get("limit")??50)||50));const page=Math.max(1,Number(url.searchParams.get("page")??1)||1);const status=url.searchParams.get("status");const temperature=url.searchParams.get("temperature");const q=url.searchParams.get("q")?.trim();const where:Prisma.LeadWhereInput={AND:[buildLeadScopeWhere(authorization),status&&Object.values(LeadStatus).includes(status as LeadStatus)?{status:status as LeadStatus}:{status:{not:LeadStatus.ARCHIVED}},temperature&&Object.values(LeadTemperature).includes(temperature as LeadTemperature)?{temperature:temperature as LeadTemperature}:{},q?{OR:[{company:{contains:q}},{contactName:{contains:q}},{leadNumber:{contains:q}}]}:{}]};const [items,total]=await Promise.all([prisma.lead.findMany({where,select:{id:true,leadNumber:true,company:true,contactName:true,source:true,status:true,temperature:true,score:true,ownerId:true,nextFollowUpAt:true,updatedAt:true},orderBy:[{updatedAt:"desc"},{id:"desc"}],skip:(page-1)*limit,take:limit}),prisma.lead.count({where})]);return NextResponse.json({data:items,page:{page,pageSize:limit,total,hasMore:page*limit<total},meta:{correlationId}});}catch(error){return workflowApiError(error,correlationId);}}
export async function POST(request:Request){const correlationId=workflowCorrelationId(request);const session=await getSession();if(!session)return workflowUnauthenticated(correlationId);const key=requireIdempotencyKey(request,correlationId);if(key instanceof NextResponse)return key;try{const authorization=await loadAuthorizationContext({actorId:session.id,legacyRole:session.role});const result=await createLeadRuntime().create({...session,authorization},createPayload(await request.json()),correlationId,key);return NextResponse.json({data:result,meta:{correlationId}},{status:201});}catch(error){return workflowApiError(error,correlationId);}}
