import { ProspectSource, ProspectStatus } from "@prisma/client";
import { z } from "zod";

const optionalText = (max: number) => z.string().trim().max(max).optional().or(z.literal(""));
const nonnegativeMoney = z.string().regex(/^\d+(\.\d{1,4})?$/).optional().or(z.literal(""));
export const prospectContactSchema = z.strictObject({ name: z.string().trim().min(2).max(255), position: optionalText(191), department: optionalText(191), phone: optionalText(100), mobile: optionalText(100), email: z.union([z.string().trim().email(), z.literal("")]).optional(), lineId: optionalText(191), preferredContactChannel: z.enum(["PHONE", "MOBILE", "EMAIL", "LINE", "MEETING", "OTHER"]).optional(), isPrimary: z.boolean().default(false) }).refine(value => Boolean(value.phone || value.mobile || value.email || value.lineId), { message: "ต้องมีช่องทางติดต่ออย่างน้อยหนึ่งรายการ", path: ["email"] });
export const prospectCommandSchema = z.strictObject({
  companyName: z.string().trim().min(2).max(255), companyNameEnglish: optionalText(255), taxId: z.union([z.string().regex(/^\d{13}$/), z.literal("")]).optional(), branchNumber: optionalText(20), customerType: optionalText(100), organizationType: optionalText(100), industryId: optionalText(191), subIndustry: optionalText(191), companySize: optionalText(100), numberOfEmployees: z.number().int().min(0).optional(), estimatedAnnualRevenue: nonnegativeMoney, website: z.union([z.string().url(), z.literal("")]).optional(), companyDescription: optionalText(10_000), address: optionalText(10_000), subDistrict: optionalText(191), district: optionalText(191), province: optionalText(191), postalCode: optionalText(20), region: optionalText(100), latitude: z.string().regex(/^-?\d+(\.\d+)?$/).optional().or(z.literal("")), longitude: z.string().regex(/^-?\d+(\.\d+)?$/).optional().or(z.literal("")), salesTerritoryId: optionalText(191), responsibleBusinessUnitId: optionalText(191), currentTelecomProvider: optionalText(10_000), currentInternetProvider: optionalText(10_000), currentCloudProvider: optionalText(10_000), currentSecurityProvider: optionalText(10_000), existingSolutions: optionalText(10_000), currentContractEndDate: z.coerce.date().optional(), numberOfBranches: z.number().int().min(0).optional(), businessPainPoints: optionalText(10_000), expectedBudget: nonnegativeMoney, expectedPurchasePeriod: optionalText(191), estimatedOpportunityValue: nonnegativeMoney, procurementMethod: optionalText(191), projectType: optionalText(191), source: z.enum(ProspectSource), sourceName: optionalText(255), campaignId: optionalText(191), referralName: optionalText(255), partnerId: optionalText(191), sourceReference: optionalText(500), backupOwnerId: optionalText(191), salesTeamId: optionalText(191), salesManagerId: optionalText(191), nextFollowUpAt: z.coerce.date().optional(), status: z.enum(ProspectStatus).default("NEW"), recommendedProducts: optionalText(10_000), notes: optionalText(10_000), contact: prospectContactSchema.optional(), duplicateOverrideReason: optionalText(1000),
});
export type ProspectCommand = z.infer<typeof prospectCommandSchema>;
