import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const schema=readFileSync("prisma/schema.prisma","utf8"),migration=readFileSync("prisma/migrations/20260715003000_add_opportunity_related_information/migration.sql","utf8"),api=readFileSync("app/api/v1/opportunities/[id]/[collection]/route.ts","utf8"),page=readFileSync("app/(portal)/opportunities/[id]/page.tsx","utf8"),forms=readFileSync("components/opportunity-related-forms.tsx","utf8"),assistance=readFileSync("components/form-field-assistance.tsx","utf8"),risk=readFileSync("components/deal-risk-panel.tsx","utf8"),css=readFileSync("app/globals.css","utf8");
describe("Opportunity related information contracts",()=>{
  it("defines structured indexed records and decimal competitor pricing",()=>{for(const model of ["OpportunityPainPoint","OpportunityRequirement","OpportunityStakeholder","OpportunityCompetitor","OpportunityRelatedCommandReceipt"])expect(schema).toContain(`model ${model}`);expect(schema).toContain("estimatedPrice    Decimal?");expect(migration).toContain("DECIMAL(19,4)");});
  it("uses authenticated scoped idempotent REST mutations",()=>{expect(api).toContain("getSession()");expect(api).toContain("loadAuthorizationContext");expect(api).toContain("requireIdempotencyKey");expect(api).toContain("createOpportunityRelatedRuntime");});
  it("renders all related sections and responsive forms",()=>{for(const value of ["Pain Points &amp; Requirements","Stakeholder Map","Competitors &amp; Win Strategy","OpportunityRelatedForms"])expect(page).toContain(value);expect(css).toContain(".related-information { display:grid");expect(css).toContain(".related-accordions form { grid-template-columns:1fr; }");});
  it("makes long requirements expandable and uses compact add affordances with help",()=>{expect(page).toContain('className="detail-value" data-expandable-text');expect(page).toContain('<p data-expandable-text>{item.description}</p>');expect(forms).toContain("function RelatedSummary");expect(forms).toContain("+ เพิ่ม");expect(forms).toContain("คำอธิบาย");expect(forms).not.toContain("เพิ่มปัญหาและผลกระทบ</span>");});
  it("keeps generated help icons inline immediately after field labels",()=>{expect(assistance).toContain("function helpAnchorForLabel");expect(assistance).toContain(":scope > span:not(.required):not(.sr-only)");expect(assistance).toContain("helpAnchorForLabel(label, labelText).append(help)");expect(css).toContain(".field-label-content { width:max-content;max-width:100%;min-width:0;display:inline-flex;align-items:center");});
  it("shows the canonical workflow path before the workspace and presents deal risk as AI Insight",()=>{expect(page).toContain("OpportunityWorkflowPath");expect(page.indexOf('id="workflow"')).toBeLessThan(page.indexOf('id="overview"'));expect(css).toContain(".workflow-path-step.current");expect(risk).toContain("AI Insight");expect(risk).toContain("อัปเดต AI Insight");expect(risk).not.toContain("Deterministic Deal Risk");});
});
