import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const schema=readFileSync("prisma/schema.prisma","utf8");const migration=readFileSync("prisma/migrations/20260715150000_add_solution_design_site_survey_boq/migration.sql","utf8");const permissionMigration=readFileSync("prisma/migrations/20260823192000_backfill_presales_permissions/migration.sql","utf8");const service=readFileSync("lib/solution-design/solution-design-service.ts","utf8");const seed=readFileSync("prisma/seed.ts","utf8");
describe("Phase 1 presales persistence and workflow contract",()=>{
  it("extends the existing SolutionDesign and records the forward-only recovery migration",()=>{expect(schema.match(/model SolutionDesign \{/g)).toHaveLength(1);for(const model of ["ServiceCategoryConfig","SolutionInstallationSite","SiteSurveyRequest","SiteSurveyResult","SiteSurveyEstimatedItem","BoqHeader","BoqItem","SolutionRequirementMapping"])expect(schema).toContain(`model ${model}`);expect(migration).toContain("Recovery note: Product/SolutionDesign alters");expect(migration).toMatch(/CREATE TABLE (?:IF NOT EXISTS )?`SiteSurveyRequest`/);expect(migration).toMatch(/CREATE TABLE (?:IF NOT EXISTS )?`BoqItem`/);});
  it("uses decimal fields and source uniqueness for BOQ idempotency",()=>{expect(schema).toMatch(/quantity\s+Decimal\s/);expect(schema).toContain("@@unique([boqId, sourceType, sourceReferenceId])");expect(service).toContain('sourceType:"SITE_SURVEY",sourceReferenceId:item.id');expect(service).toContain("calculateBoqTotals");});
  it("keeps status, survey rules, approval capability and BOQ sections configurable",()=>{expect(schema).toContain("model SolutionStatusDefinition");expect(schema).toContain("model SolutionStatusTransition");expect(seed).toContain('entityType:"SITE_SURVEY"');expect(seed).toContain('HARD_INFRASTRUCTURE:"Hard Infrastructure"');expect(seed).toContain("requiresSiteSurvey:false");expect(seed).toContain("solution-design.technical.approve");expect(seed).toContain("boqSections");});
  it("backfills Presales page access without replacing existing grants",()=>{expect(permissionMigration).toContain("INSERT IGNORE INTO `RolePermissionGrant`");expect(permissionMigration).toContain("navigation.solution-designs.view");expect(permissionMigration).toContain("navigation.site-surveys.view");expect(permissionMigration).toContain("navigation.boqs.view");expect(permissionMigration).toContain("'ADMIN', admin_permissions.permissionCode");expect(permissionMigration).toContain("'solution-design.view'");expect(permissionMigration).toContain("'site-survey.view'");expect(permissionMigration).toContain("'boq.view'");expect(permissionMigration).not.toMatch(/DELETE|DROP|TRUNCATE/i);expect(seed).toMatch(/presalesPermissionMatrix[^;]*ADMIN:\["solution-design\.view"/);expect(seed).toMatch(/COVERAGE:\[[^\]]*"boq\.view"/);});
  it("writes critical actions to the append-only audit inside transactions",()=>{for(const action of ["solution-design.create","solution-design.survey-requirement.override","site-survey.submit","site-survey.assign","site-survey.result.manual-entry","boq.create-from-survey"])expect(service).toContain(action);expect(service).toContain("site-survey.result.${decision.toLowerCase()}");expect(service).toContain("{transaction:tx}");});
});
