import { FileSignature, Pencil } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { QuoteDocumentActions } from "@/components/quote-document-actions";
import { QuoteCommercialTransitionForm, QuoteSubmitForm } from "@/components/workflow-forms";
import { requireSession } from "@/lib/auth";
import { loadAuthorizationContext } from "@/lib/authorization/authorization-context";
import { PERMISSIONS, permissionPolicy } from "@/lib/authorization/permission-policy";
import { isQuoteApprovalEnabled } from "@/lib/commercial/quote-runtime";
import { buildOpportunityScopeWhere } from "@/lib/opportunity/opportunity-query";
import { prisma } from "@/lib/prisma";

const money=(value:{toString():string},currency:string)=>new Intl.NumberFormat("th-TH",{style:"currency",currency,minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value));
const quantity=(value:{toString():string})=>new Intl.NumberFormat("th-TH",{minimumFractionDigits:0,maximumFractionDigits:4}).format(Number(value));
const date=(value:Date|null|undefined)=>value?.toLocaleDateString("th-TH",{dateStyle:"long",timeZone:"Asia/Bangkok"})??"—";

export default async function QuoteDetail({params}:{params:Promise<{id:string}>}){
  const session=await requireSession();const approvalEnabled=await isQuoteApprovalEnabled();const context=await loadAuthorizationContext({actorId:session.id,legacyRole:session.role});const{id}=await params;
  const quote=await prisma.quote.findFirst({where:{id,opportunity:buildOpportunityScopeWhere(context)},include:{customer:{include:{contacts:{where:{isPrimary:true},take:1}}},opportunity:{include:{owner:{select:{name:true,email:true}}}},proposal:{select:{id:true,proposalNo:true,name:true}},maker:{select:{name:true,email:true}},versions:{orderBy:{versionNumber:"desc"},include:{items:true,approvalRequests:{include:{steps:true}}}}}});
  if(!quote||!quote.versions.length)notFound();
  const latest=quote.versions[0];const canManage=permissionPolicy.allows(session,PERMISSIONS.quoteManage);const canEdit=canManage;const canConvert=latest.status==="ACCEPTED"&&permissionPolicy.allows(session,PERMISSIONS.contractManage);const primaryContact=quote.customer.contacts[0];
  return <>
    <div className="page-head quote-screen-only"><div><p className="eyebrow">Commercial · Versioned Quotation</p><h1>{quote.quoteNo}</h1><p>{quote.customer.name} · Version {latest.versionNumber}</p></div><div className="actions quote-detail-actions"><QuoteDocumentActions quoteNo={`${quote.quoteNo}-v${latest.versionNumber}`}/>{canEdit&&<Link className="secondary" href={`/quotes/new?quoteId=${quote.id}`}><Pencil aria-hidden="true"/>แก้ไขรายละเอียด</Link>}{canConvert?<Link className="secondary" href={`/contracts/new?quoteVersionId=${latest.id}`}><FileSignature aria-hidden="true"/>Convert to Contract</Link>:<button type="button" className="secondary disabled" disabled title={latest.status!=="ACCEPTED"?"เปลี่ยน Status เป็น ACCEPTED ก่อนสร้างสัญญา":"คุณไม่มีสิทธิ์สร้างสัญญา"}><FileSignature aria-hidden="true"/>Convert to Contract</button>}</div></div>
    {!approvalEnabled&&<p className="notice quote-screen-only">ระบบ Approval ของ Quotation ถูกพักไว้ชั่วคราว ผู้มีสิทธิ์แก้ไขสามารถกำหนด Status ใน version ใหม่ได้ และทุกการเปลี่ยนแปลงจะถูกบันทึกใน Audit</p>}
    <article className="quotation-document" aria-label={`Quotation ${quote.quoteNo}`}>
      <header className="quotation-letterhead"><div className="quotation-brand"><span aria-hidden="true">nt</span><div><strong>NT Enterprise Sales</strong><small>Commercial Quotation</small></div></div><div className="quotation-title"><h1>ใบเสนอราคา</h1><p>QUOTATION</p></div></header>
      <section className="quotation-meta-grid"><div><span>เลขที่ใบเสนอราคา</span><strong>{quote.quoteNo}</strong></div><div><span>Version</span><strong>{latest.versionNumber}</strong></div><div><span>วันที่ออกเอกสาร</span><strong>{date(latest.createdAt)}</strong></div><div><span>ใช้ได้ถึง</span><strong>{date(latest.validUntil)}</strong></div><div><span>สถานะ</span><strong>{latest.status}</strong></div><div><span>สกุลเงิน</span><strong>{latest.currency}</strong></div></section>
      <section className="quotation-parties"><div><h2>เสนอราคาให้ / Quotation To</h2><strong>{quote.customer.name}</strong><p>{quote.customer.address||"ยังไม่ระบุที่อยู่ลูกค้า"}</p><p>เลขประจำตัวผู้เสียภาษี: {quote.customer.taxId}</p>{primaryContact&&<p>ผู้ติดต่อ: {primaryContact.name}{primaryContact.phone?` · ${primaryContact.phone}`:""}{primaryContact.email?` · ${primaryContact.email}`:""}</p>}</div><div><h2>ข้อมูลอ้างอิง / Reference</h2><p>Opportunity: <strong>{quote.opportunity?.name??"—"}</strong></p>{quote.proposal&&<p>Proposal: <strong>{quote.proposal.proposalNo} · {quote.proposal.name}</strong></p>}<p>ผู้ดูแล: <strong>{quote.opportunity?.owner.name??quote.maker?.name??"—"}</strong></p><p>{quote.opportunity?.owner.email??quote.maker?.email??""}</p></div></section>
      <div className="quotation-items-wrap"><table className="quotation-items"><thead><tr><th>#</th><th>รหัส</th><th>รายละเอียดสินค้า / บริการ</th><th>จำนวน</th><th>ราคาต่อหน่วย</th><th>ส่วนลด</th><th>จำนวนเงิน</th></tr></thead><tbody>{latest.items.map((item,index)=><tr key={item.id}><td>{index+1}</td><td>{item.productCode}</td><td><strong>{item.productName}</strong></td><td>{quantity(item.quantity)}</td><td>{money(item.unitPrice,latest.currency)}</td><td>{money(item.discountAmount,latest.currency)}</td><td>{money(item.lineTotal,latest.currency)}</td></tr>)}</tbody></table></div>
      <section className="quotation-summary-block"><div className="quotation-notes"><h2>หมายเหตุและเงื่อนไข</h2><p>{latest.notes||"ราคานี้มีผลถึงวันที่ระบุในเอกสาร และเป็นไปตามเงื่อนไขการขายที่ได้รับอนุมัติ"}</p></div><dl><div><dt>รวมเป็นเงิน</dt><dd>{money(latest.subtotal,latest.currency)}</dd></div><div><dt>ส่วนลด</dt><dd>{money(latest.discountAmount,latest.currency)}</dd></div><div className="quotation-grand-total"><dt>ยอดสุทธิ</dt><dd>{money(latest.total,latest.currency)}</dd></div></dl></section>
      <footer className="quotation-signatures"><div><span>ผู้เสนอราคา / Prepared by</span><strong>{quote.maker?.name??quote.opportunity?.owner.name??"—"}</strong><small>วันที่ ____________________</small></div><div><span>ผู้มีอำนาจอนุมัติ / Authorized by</span><strong>____________________________</strong><small>วันที่ ____________________</small></div><div><span>ผู้ยอมรับใบเสนอราคา / Accepted by</span><strong>____________________________</strong><small>วันที่ ____________________</small></div></footer>
    </article>
    <section className="quote-workflow-layout quote-screen-only"><div className="card"><div className="card-header"><div><strong>Quotation Status</strong><small>{approvalEnabled?"สถานะเปลี่ยนได้ตาม governed transition เท่านั้น":"แก้ไขรายละเอียดเพื่อกำหนด Status ใหม่"}</small></div><span className="badge">{latest.status}</span></div><div className="card-body actions">{approvalEnabled&&latest.status==="DRAFT"&&canManage&&<QuoteSubmitForm quoteId={quote.id} quoteVersionId={latest.id}/>} {canManage&&(latest.status==="APPROVED"||latest.status==="SENT")&&<QuoteCommercialTransitionForm quoteId={quote.id} quoteVersionId={latest.id} status={latest.status}/>} {canEdit&&<Link className="secondary" href={`/quotes/new?quoteId=${quote.id}`}>สร้าง Version ใหม่ / แก้ Status</Link>} {!approvalEnabled&&latest.status==="DRAFT"&&<p className="help">กำหนด Status ได้จากหน้าแก้ไขรายละเอียดระหว่างที่ Approval Control Center ปิดอยู่</p>}</div></div>
      {session.role!=="VIEWER"&&<section className="card"><div className="card-header"><strong>Internal Commercial Summary</strong></div><div className="card-body detail-grid"><div><p className="detail-label">Total cost</p><p className="detail-value">{money(latest.totalCost,latest.currency)}</p></div><div><p className="detail-label">Gross margin</p><p className="detail-value">{latest.grossMarginPct.toFixed(4)}%</p></div></div></section>}
    </section>
    <section className="card quote-version-history quote-screen-only"><div className="card-header"><div><strong>Version History</strong><small>ทุก version เดิมเก็บเป็นหลักฐานและแก้ไขย้อนหลังไม่ได้</small></div><span>{quote.versions.length} versions</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Version</th><th>Status</th><th>Created</th><th>Valid until</th><th>Total</th><th>Approval</th></tr></thead><tbody>{quote.versions.map(version=><tr key={version.id}><td>v{version.versionNumber}</td><td><span className="badge muted">{version.status}</span></td><td>{date(version.createdAt)}</td><td>{date(version.validUntil)}</td><td>{money(version.total,version.currency)}</td><td>{version.approvalRequests.map(request=><Link className="link" href={`/approvals/${request.id}`} key={request.id}>{request.status}</Link>)}{!version.approvalRequests.length&&"—"}</td></tr>)}</tbody></table></div></section>
  </>;
}
